<?php

/**
* list.phtml
* 
* list view file
* 
* @project mvc 
* @author duong bien
* @email bien.duongvan@yahoo.com 
* @date 16/7/2015
* @time 11:41
* @copyright 2015 Copyright duong bien
* @license duong bien
* @version 1.0.0
*/

?>
<div class="row">
    <div class="col-lg-12">
        <ul class="breadcrumb">
            <li><a href="<?php echo BASE_URL.'admin'?>">Quản trị</a></li>
            <li class="active">Danh sách các action</li>
        </ul>
    </div>
</div>

<form action="" id="addUserForm" method="post" enctype="multipart/form-data">
<div class="col-sm-12">
    <div class="row">
        <h3>Thêm Action mới</h3>
        <div class="form-group">
            <label>Tên Action</label>
            <input class="form-control" type="text" name="action_name" id="action_name" />
        </div>
        <?php if(count($controller)>0):?>
        <div class="form-group">
            <label>Controller</label>
            <select class="form-control" name="controller_name" id="controller_name">
                <option value="">----</option>
                <?php foreach($controller as $file):?>
                <option value="<?php echo $file;?>"><?php echo $file;?></option>
                <?php endforeach;?>
            </select>
        </div> 
        <?php endif;?>
        <div class="form-group">
            <input class="btn btn-primary btn-sm" type="submit" value="Lưu" />
        </div>  
    </div>
</div>
</form>

<h3>Danh sách các Action</h3>
<div class="row">

<?php if(count($actions) == 0):?>
<p class="no-data"><?php echo NODATA;?></p>
<?php else:?>
    <div class="col-lg-12">  
        <div class="col-sm-12">
            <div class="row">
                <table id="dataTables-example" class="table table-striped table-bordered table-hover dataTable">
                    <thead>
                        <tr>
                            <th class="text-center" style="width: 50px;">ID</th>
                            <th class="">Tên Action</th>
                            <th class="" style="width: 300px;">Tên Controller</th>
                            <th class="text-center" style="width: 100px;">Thao tác</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php foreach($actions as $row):?>
                        <tr class="grade odd">
                            <td class="text-center"><?php echo $row['ACTION_ID'];?></td>
                            <td><?php echo $row['ACTION_NAME'];?></td>
                            <td><?php echo $row['CONTROLLER_NAME'];?></td>
                            <td class="text-center">
                            <?php if($acl->allow("permission","delete_action")):?>
                                <a onclick="return confirm('Xóa bản ghi này?');" href="<?php echo BASE_URL;?>permission/delete_action?id=<?php echo $row['ACTION_ID'];?>">Xóa</a>
                            <?php endif;?>
                            </td>
                        </tr>
                        
                    <?php endforeach;?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
<?php endif;?>
</div>


<script type="text/javascript">

$(document).ready(function() {
    $('#addUserForm').validate({
		rules: {
			action_name: {
				required: true
			}
	    },
	    messages: {
	    	// Enter custom error text here.
		}
	});
    
    $('#controller_name').selectpicker({
          liveSearch: false,
          maxOptions: 1
    });
});

</script>