        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->
    <div class="container-fluid">
        <div class="row">
            <div class="text-center" style="padding: 10px 0;">
                <?php echo Core_Config::getConfig('web','copyright');?>
            </div>
        </div>
    </div>
    <iframe name="iframe-temp" style = "
    position:absolute;
    width:0;
    height:0;
    border: none;
    padding: 0;
    margin: 0
    "></iframe>
    
    <div class="overlay"></div>



        <script type="text/javascript">
            var requirewarnning = "<?php $mbftext->__('Không được bỏ trống trường này!'); ?>";
            $(document).ready(function () {


            });

        </script>
</body>

</html>
