<?php 
$acl = new Core_Acl();
//echo '<pre>';
//print_r($acl);
?>
<!DOCTYPE html>
<html lang="en">
<head>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><?php echo isset($title) ? $title : Core_Config::getConfig("web","default_title");?></title>

    <!-- Bootstrap Core CSS -->
    <link href="<?php echo SKIN_URL;?>/admin/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="<?php echo SKIN_URL;?>/admin/bower_components/metisMenu/dist/metisMenu.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="<?php echo SKIN_URL;?>/admin/dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="<?php echo SKIN_URL;?>/admin/bower_components/morrisjs/morris.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="<?php echo SKIN_URL;?>/admin/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <script type="text/javascript">
        var baseUrl = "<?php echo BASE_URL;?>";
    </script>
    <!-- jQuery -->
    <script type="text/javascript" src="<?php echo SKIN_URL;?>/admin/bower_components/jquery/dist/jquery.min.js"></script>
    
    <!-- Bootstrap Core JavaScript -->
    <script type="text/javascript" src="<?php echo SKIN_URL;?>/admin/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script type="text/javascript" src="<?php echo SKIN_URL;?>/admin/bower_components/metisMenu/dist/metisMenu.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script type="text/javascript" src="<?php echo SKIN_URL;?>/admin/dist/js/sb-admin-2.js"></script>
    
    <!-- Jquery Validate -->
    <script type="text/javascript" src="<?php echo SKIN_URL;?>/admin/js/jquery.validate/jquery.validate.js"></script>
    
    <!-- Jquery UI -->
    <link href="<?php echo SKIN_URL;?>/admin/js/jquery.ui/jquery-ui.css" rel="stylesheet"/>
    <script type="text/javascript" src="<?php echo SKIN_URL;?>/admin/js/jquery.ui/jquery-ui.js"></script>

    <!-- Tinymce / Moxiemanager-->
    <script type="text/javascript" src="<?php echo SKIN_URL;?>/admin/js/tinymce/tinymce.min.js"></script>
    <script type="text/javascript" src="<?php echo SKIN_URL;?>/admin/js/moxiemanager/js/moxman.loader.min.js"></script>
    
    <!-- Bootstrap Select -->
    <link rel="stylesheet" href="<?php echo SKIN_URL;?>/admin/bootstrap_select/dist/css/bootstrap-select.css">
    <script src="<?php echo SKIN_URL;?>/admin/bootstrap_select/dist/js/bootstrap-select.js"></script>
    
    <!-- Admin Custom -->
    <script type="text/javascript" src="<?php echo SKIN_URL;?>/admin/js/smalljs.js"></script>
    <script type="text/javascript" src="<?php echo SKIN_URL;?>/admin/js/ajax.js"></script>
    <script type="text/javascript" src="<?php echo SKIN_URL;?>/admin/js/function.js"></script>

    <script type="text/javascript" src="<?php echo SKIN_URL;?>/admin/js/jquery.cookie/jquery.cookie.js"></script>
    
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    
    <script type="text/javascript">
        $(document).ajaxStart(function () {
            $(document.body).css({'cursor': 'wait'});
        });
        $(document).ajaxComplete(function () {
            $(document.body).css({'cursor': 'default'});
        });
    </script>
    
    <script type="text/javascript">

    $(document).ready(function() {    
        $('select').selectpicker({
              liveSearch: false,
              maxOptions: 1
        }); 
    });
    
    </script>

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo BASE_URL;?>admin">
                    <img style="height: 40px;" src="<?php echo Core_Config::getConfig('web','logo');?>" lang="<?php echo Core_Config::getConfig('web','site_name');?>" title="<?php echo Core_Config::getConfig('web','site_name');?>" />
                </a>
                <a style="font-size: 12px;font-weight: bold;line-height: 40px;margin-left: 20px;" class="navbar-brand"><?php echo Core_Config::getConfig("web","service_name")?></a>
            </div>
            <!-- /.navbar-header -->
            
            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-tasks fa-fw"></i> Hệ thống <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-tasks">
                        <?php echo Core_System::calculateDisk();?>
                        
                    </ul>
                    <!-- /.dropdown-tasks -->
                </li>
                <li class="dropdown">
                    <a href="javascript:;">
                        <i class="fa fa-user fa-fw"></i> <?php echo Core_Login::getFullName();?>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="<?php echo BASE_URL.'user/edit?id='.Core_Login::getUserId();?>"><i class="fa fa-gear fa-fw"></i> Sửa thông tin</a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="<?php echo BASE_URL.'login/logout'?>"><i class="fa fa-sign-out fa-fw"></i> Thoát</a>
                </li>
            </ul>
            <!-- /.navbar-top-links -->
            
            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <a href="<?php echo BASE_URL;?>admin"><i class="fa fa-dashboard fa-fw"></i> Quản trị</a>
                        </li>
                        
                        <?php if($acl->allow("system","config")):?>
                        <li class="menu-bctk">
                            <a href="javascript:;"><i class="fa fa-th-list fa-fw"></i> Cấu hình<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li class="menu-bctk">
                                    <?php if($acl->allow("system","config")):?>
                                        <a href="<?php echo BASE_URL;?>system/config"><i class="fa  fa-caret-right fa-fw"></i> Hệ thống</a>
                                    <?php endif;?>
                                </li>
                            </ul>
                        </li>
                        <?php endif;?> 

                        <?php if($acl->allow("group","list") || 
                                $acl->allow("user","list") || 
                                $acl->allow("user","add") || 
                                $acl->allow("permission","action") || 
								$acl->allow("impactlogs","list")):
                        ?>
                        <li class="menu-user">
                            <a href="javascript:;"><i class="fa fa-user fa-fw"></i> Người dùng<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <?php if($acl->allow("group","list")):?>
                                <li class="menu-user">
                                    <a href="<?php echo BASE_URL.'group/list'?>"><i class="fa  fa-caret-right fa-fw"></i> Danh sách nhóm</a>
                                </li>
                                <?php endif;?>
                                <li class="menu-user">
                                    <?php if($acl->allow("user","list")):?>
                                    <a href="<?php echo BASE_URL.'user/list'?>"><i class="fa  fa-caret-right fa-fw"></i> Danh sách người dùng</a>
                                    <?php endif;?>
                                </li>
                                <?php if($acl->allow("permission","action")):?>
                                <li class="menu-user">
                                    <a href="<?php echo BASE_URL.'permission/action'?>"><i class="fa  fa-caret-right fa-fw"></i> Danh sách action</a>
                                </li>
                                <?php endif;?>
								<?php if($acl->allow("impactlogs","list")):?>
                                <li class="menu-user">
                                    <a href="<?php echo BASE_URL.'impactlogs/list'?>"><i class="fa  fa-caret-right fa-fw"></i> Logs tác động hệ thống</a>
                                </li>
                                <?php endif;?>
                            </ul>
                        </li>
                        <?php endif;?>
						
						<?php if($acl->allow("message","list") || 
                                $acl->allow("errorcode","list") || 
								$acl->allow("blacklistreason","list")):
                        ?>
                        <li class="menu-user">
                            <a href="javascript:;"><i class="fa fa-th-list fa-fw"></i> Danh mục<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li class="menu-user">
									<?php if($acl->allow("errorcode","list")):?>
                                    <a href="<?php echo BASE_URL.'errorcode/list'?>"><i class="fa  fa-caret-right fa-fw"></i> Danh sách mã lỗi hệ thống</a>
                                    <?php endif;?>
                                    <?php if($acl->allow("message","list")):?>
                                    <a href="<?php echo BASE_URL.'message/list'?>"><i class="fa  fa-caret-right fa-fw"></i> Danh sách các Message</a>
                                    <?php endif;?>
									<?php if($acl->allow("blacklistreason","list")):?>
                                    <a href="<?php echo BASE_URL.'blacklistreason/list'?>"><i class="fa  fa-caret-right fa-fw"></i> Danh sách lý do Blacklist</a>
                                    <?php endif;?>
                                </li>
                            </ul>
                        </li>
                        <?php endif;?>
						
						<?php if($acl->allow("quanlybpm","lich_chay_process") || 
						$acl->allow("quanlybpm","cau_hinh_process_bpm") || 
						$acl->allow("quanlybpm","tra_cuu_process_execution")):
                        ?>
                        <li class="menu-user">
                            <a href="javascript:;"><i class="fa fa-th-list fa-fw"></i> Quản ly BPM<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li class="menu-user">
									<?php if($acl->allow("quanlybpm","lich_chay_process")):?>
                                    <a href="<?php echo BASE_URL.'quanlybpm/lich_chay_process'?>"><i class="fa  fa-caret-right fa-fw"></i> Lịch chạy process</a>
                                    <?php endif;?>
                                    <?php if($acl->allow("quanlybpm","cau_hinh_process_bpm")):?>
                                    <a href="<?php echo BASE_URL.'quanlybpm/cau_hinh_process_bpm'?>"><i class="fa  fa-caret-right fa-fw"></i> Cấu hình process BPM</a>
                                    <?php endif;?>
									<?php if($acl->allow("quanlybpm","tra_cuu_process_execution")):?>
                                    <a href="<?php echo BASE_URL.'quanlybpm/tra_cuu_process_execution'?>"><i class="fa  fa-caret-right fa-fw"></i> Tra cứu process excution</a>
                                    <?php endif;?>
                                </li>
                            </ul>
                        </li>
                        <?php endif;?>
						
						<?php if($acl->allow("defineagelevel","list") || 
						$acl->allow("definerules","list") || 
						$acl->allow("defineusagelevel","list")):
                        ?>
                        <li class="menu-user">
                            <a href="javascript:;"><i class="fa fa-th-list fa-fw"></i> Cấu hình điều kiện ứng thẻ<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li class="menu-user">
									<?php if($acl->allow("defineagelevel","list")):?>
                                    <a href="<?php echo BASE_URL.'defineagelevel/list'?>"><i class="fa  fa-caret-right fa-fw"></i> Định nghĩa mức tuổi thọ</a>
                                    <?php endif;?>
                                    <?php if($acl->allow("defineusagelevel","list")):?>
                                    <a href="<?php echo BASE_URL.'defineusagelevel/list'?>"><i class="fa  fa-caret-right fa-fw"></i> Định nghĩa mức tiêu dùng</a>
                                    <?php endif;?>
									<?php if($acl->allow("definerules","list")):?>
                                    <a href="<?php echo BASE_URL.'definerules/list'?>"><i class="fa  fa-caret-right fa-fw"></i> Cấu hình quy tắc điều kiện ứng</a>
                                    <?php endif;?>
                                </li>
                            </ul>
                        </li>
                        <?php endif;?>
						
						<?php if($acl->allow("systemparam","list")):?>
                        <li class="menu-user">
                            <a href="javascript:;"><i class="fa fa-th-list fa-fw"></i> Điều khiển hệ thống<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li class="menu-user">
                                    <?php if($acl->allow("systemparam","list")):?>
                                        <a href="<?php echo BASE_URL.'systemparam/list'?>"><i class="fa  fa-caret-right fa-fw"></i> Khai báo Event</a>
                                    <?php endif;?>
                                    <?php if($acl->allow("systemparam","list")):?>
                                        <a href="<?php echo BASE_URL.'systemparam/list'?>"><i class="fa  fa-caret-right fa-fw"></i> Tạo event trigger</a>
                                    <?php endif;?>
                                    <?php if($acl->allow("systemparam","list")):?>
                                        <a href="<?php echo BASE_URL.'systemparam/list'?>"><i class="fa  fa-caret-right fa-fw"></i> Tra cứu event log</a>
                                    <?php endif;?>
									<?php if($acl->allow("systemparam","list")):?>
                                    <a href="<?php echo BASE_URL.'systemparam/list'?>"><i class="fa  fa-caret-right fa-fw"></i> Hiệu chỉnh tham số hệ thống</a>
                                    <?php endif;?>
                                </li>
                            </ul>
                        </li>
                        <?php endif;?>
						
						<?php if($acl->allow("complain","xoa_no_do_khieu_nai") || 
								$acl->allow("complain","bu_the_do_khieu_nai") || 
								$acl->allow("complain","dua_thue_bao_vao_blacklist") || 
								$acl->allow("complain","danh_sach_blacklist")):?>
                        <li class="menu-user">
                            <a href="javascript:;"><i class="fa fa-th-list fa-fw"></i> Giải quyết KN cho quản trị<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li class="menu-user">
                                    <?php if($acl->allow("complain","xoa_no_do_khieu_nai")):?>
                                        <a href="<?php echo BASE_URL.'complain/xoa_no_do_khieu_nai'?>"><i class="fa  fa-caret-right fa-fw"></i> Xóa nợ do khiếu nại</a>
                                    <?php endif;?>
                                    <?php if($acl->allow("complain","bu_the_do_khieu_nai")):?>
                                        <a href="<?php echo BASE_URL.'complain/bu_the_do_khieu_nai'?>"><i class="fa  fa-caret-right fa-fw"></i> Bù thẻ mới do khiếu nại</a>
                                    <?php endif;?>
									<?php if($acl->allow("complain","dua_thue_bao_vao_blacklist")):?>
                                        <a href="<?php echo BASE_URL.'complain/dua_thue_bao_vao_blacklist'?>"><i class="fa  fa-caret-right fa-fw"></i> Đưa thuê bao vào blacklist</a>
                                    <?php endif;?>
									<?php if($acl->allow("complain","danh_sach_blacklist")):?>
                                        <a href="<?php echo BASE_URL.'complain/danh_sach_blacklist'?>"><i class="fa  fa-caret-right fa-fw"></i> Danh sách thuê bao black list</a>
                                    <?php endif;?>
                                </li>
                            </ul>
                        </li>
                        <?php endif;?>
						
						<?php if($acl->allow("search","muc_the_ung") | 
								$acl->allow("search","giao_dich_ung_the") | 
								$acl->allow("search","giao_dich_hoan_ung") | 
								$acl->allow("search","tra_cuu_no") | 
								$acl->allow("search","danh_sach_blacklist") | 
								$acl->allow("search","thong_tin_thue_bao") | 
								$acl->allow("search","trang_thai_the_cao") | 
								$acl->allow("search","sms_log")):?>
                        <li class="menu-user">
                            <a href="javascript:;"><i class="fa fa-th-list fa-fw"></i> Tra cứu<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li class="menu-user">
									<?php if($acl->allow("search","muc_the_ung")):?>
                                    <a href="<?php echo BASE_URL.'search/muc_the_ung'?>"><i class="fa  fa-caret-right fa-fw"></i> Mức thẻ ứng áp dụng cho TB</a>
                                    <?php endif;?>
									
									<?php if($acl->allow("search","giao_dich_ung_the")):?>
                                    <a href="<?php echo BASE_URL.'search/giao_dich_ung_the'?>"><i class="fa  fa-caret-right fa-fw"></i> Giao dịch ứng thẻ</a>
                                    <?php endif;?>
									
									<?php if($acl->allow("search","giao_dich_hoan_ung")):?>
                                    <a href="<?php echo BASE_URL.'search/giao_dich_hoan_ung'?>"><i class="fa  fa-caret-right fa-fw"></i> Giao dịch hoàn ứng</a>
                                    <?php endif;?>
									
									<?php if($acl->allow("search","tra_cuu_no")):?>
                                    <a href="<?php echo BASE_URL.'search/tra_cuu_no'?>"><i class="fa  fa-caret-right fa-fw"></i> Tra cứu nợ</a>
                                    <?php endif;?>
									
									<?php if($acl->allow("search","danh_sach_blacklist")):?>
                                    <a href="<?php echo BASE_URL.'search/danh_sach_blacklist'?>"><i class="fa  fa-caret-right fa-fw"></i> Danh sách blacklist</a>
                                    <?php endif;?>
									
									<?php if($acl->allow("search","thong_tin_thue_bao")):?>
                                    <a href="<?php echo BASE_URL.'search/thong_tin_thue_bao'?>"><i class="fa  fa-caret-right fa-fw"></i> Thông tin thuê bao</a>
                                    <?php endif;?>
									
									<?php if($acl->allow("search","trang_thai_the_cao")):?>
                                    <a href="<?php echo BASE_URL.'search/trang_thai_the_cao'?>"><i class="fa  fa-caret-right fa-fw"></i> Trạng thái thẻ cào</a>
                                    <?php endif;?>
									
									<?php if($acl->allow("search","sms_log")):?>
                                    <a href="<?php echo BASE_URL.'search/sms_log'?>"><i class="fa  fa-caret-right fa-fw"></i> Tra cứu SMS log</a>
                                    <?php endif;?>
                                </li>
                            </ul>
                        </li>
                        <?php endif;?>


                        <?php if($acl->allow("report","tongquan") || 
							$acl->allow("report","phan_tich_moi_ung") || 
							$acl->allow("report","bao_cao_the_ung") || 
							$acl->allow("report","bao_cao_thu_no") || 
							$acl->allow("report","bao_cao_kho_the")):?>
                            <li class="menu-user">
                                <a href="javascript:;"><i class="fa fa-th-list fa-fw"></i> Báo cáo thống kê<span class="fa arrow"></span></a>
                                <ul class="nav nav-second-level">
                                    <li class="menu-user">
                                        <?php if($acl->allow("report","tongquan")):?>
                                            <a href="<?php echo BASE_URL.'report/tongquan'?>"><i class="fa  fa-caret-right fa-fw"></i> Báo cáo tổng quan</a>
                                        <?php endif;?>
										<?php if($acl->allow("report","phan_tich_moi_ung")):?>
                                            <a href="<?php echo BASE_URL.'report/phan_tich_moi_ung'?>"><i class="fa  fa-caret-right fa-fw"></i> Báo cáo phân tích mời ứng</a>
                                        <?php endif;?>
										<?php if($acl->allow("report","bao_cao_the_ung")):?>
                                            <a href="<?php echo BASE_URL.'report/bao_cao_the_ung'?>"><i class="fa  fa-caret-right fa-fw"></i> Báo cáo thẻ ứng</a>
                                        <?php endif;?>
                                        <?php if($acl->allow("report","bao_cao_no_xau")):?>
                                            <a href="<?php echo BASE_URL.'report/bao_cao_no_xau'?>"><i class="fa  fa-caret-right fa-fw"></i> Báo cáo nợ xấu</a>
                                        <?php endif;?>
                                        <?php if($acl->allow("report","bieu_do_no_xau")):?>
                                            <a href="<?php echo BASE_URL.'statistics/bieu_do_no_xau'?>"><i class="fa  fa-caret-right fa-fw"></i> Biểu đồ số tiền nợ xấu theo ngày</a>
                                        <?php endif;?>
                                        <?php if($acl->allow("report","bieu_do_no_xau_tuan")):?>
                                            <a href="<?php echo BASE_URL.'statistics/bieu_do_no_xau_tuan'?>"><i class="fa  fa-caret-right fa-fw"></i> Biểu đồ số tiền nợ xấu theo tuần</a>
                                        <?php endif;?>
										<?php if($acl->allow("report","bao_cao_thu_no")):?>
                                            <a href="<?php echo BASE_URL.'report/bao_cao_thu_no'?>"><i class="fa  fa-caret-right fa-fw"></i> Báo cáo thu nợ</a>
                                        <?php endif;?>
										<?php if($acl->allow("report","bao_cao_kho_the")):?>
                                            <a href="<?php echo BASE_URL.'report/bao_cao_kho_the'?>"><i class="fa  fa-caret-right fa-fw"></i> Báo cáo kho thẻ</a>
                                        <?php endif;?>
                                    </li>
                                </ul>
                            </li>
                        <?php endif;?>

						<?php if($acl->allow("kpi","kpi_mt") || 
								$acl->allow("kpi","kpi_mo") || 
								$acl->allow("kpi","tyle_ungthe_thanhcong") || 
								$acl->allow("kpi","tyle_hoanung_thanhcong")):?>
                        <li class="menu-user">
                            <a href="javascript:;"><i class="fa fa-th-list fa-fw"></i> KPI hệ thống<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li class="menu-user">
                                    <?php if($acl->allow("kpi","kpi_mt")):?>
                                        <a href="<?php echo BASE_URL.'kpi/kpi_mt'?>"><i class="fa  fa-caret-right fa-fw"></i> Tỷ lệ MT thành công</a>
                                    <?php endif;?>
                                    <?php if($acl->allow("kpi","kpi_mo")):?>
                                        <a href="<?php echo BASE_URL.'kpi/kpi_mo'?>"><i class="fa  fa-caret-right fa-fw"></i> KPI MO</a>
                                    <?php endif;?>
									<?php if($acl->allow("kpi","tyle_ungthe_thanhcong")):?>
                                        <a href="<?php echo BASE_URL.'kpi/tyle_ungthe_thanhcong'?>"><i class="fa  fa-caret-right fa-fw"></i> Tỷ lệ ứng thẻ thành công</a>
                                    <?php endif;?>
									<?php if($acl->allow("kpi","tyle_hoanung_thanhcong")):?>
                                        <a href="<?php echo BASE_URL.'kpi/tyle_hoanung_thanhcong'?>"><i class="fa  fa-caret-right fa-fw"></i> Tỷ lệ hoàn ứng thành công</a>
                                    <?php endif;?>
                                </li>
                            </ul>
                        </li>
                        <?php endif;?>

                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <div id="page-wrapper">
  