<?php

/**
* add.phtml
* 
* add view file
* 
* @project mvc 
* @author duong bien
* @email bien.duongvan@yahoo.com 
* @date 16/7/2015
* @time 11:38
* @copyright 2015 Copyright duong bien
* @license duong bien
* @version 1.0.0
*/

?>
<div class="row">
    <div class="col-lg-12">
        <div class="row">
            <ul class="breadcrumb">
                <li><a href="<?php echo BASE_URL.'admin'?>">Quản trị</a></li>
                <li><a href="<?php echo BASE_URL.'blacklistreason/list'?>">Danh sách lý do Blacklist</a></li>
                <li class="active">Thêm lý do Blacklist mới</li>
            </ul>
            <?php if(isset($message) && ($message != null)):?>
            <div class="alert alert-success alert-dismissable">
                <button aria-hidden="true" data-dismiss="alert" class="close" type="button">x</button>
                <?php echo $message;?>
            </div>
            <?php endif;?>
        </div>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
    <div class="panel panel-default">
        <div class="panel-heading">
            <i class="fa fa-edit fa-fw"></i> 
            Nhập các thông tin về lý do Blacklist vào form dưới đây:
        </div>
        <div class="panel-body">
            <form action="" id="addBlacklistReasonForm" method="post" enctype="multipart/form-data">
                <div class="col-lg-12">
                    <div class="row">
                        <div class="col-lg-8">
                            <div class="form-group">
                                <label>REASON CODE</label>
                                <input class="form-control" type="text" name="reason_code" id="reason_code" />
                            </div>
							<div class="form-group">
                                <label>REASON NAME</label>
                                <textarea class="form-control" name="reason_name" id="reason_name"></textarea>
                            </div>
                            <div class="form-group">
                                <input class="btn btn-primary btn-sm" type="submit" value="Lưu" />
                            </div>                   
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script type="text/javascript">

$(document).ready(function() {
    $('#addBlacklistReasonForm').validate({
		rules: {
			reason_code: {
				required: true,
				remote: '<?php echo BASE_URL.'blacklistreason/check?check_type=reason_code';?>'
			},
			reason_name: {
				required: true
			}
	    },
	    messages: {
	    	// Enter custom error text here.
		}
	});
});

</script>