<?php

/**
 * list.phtml
 *
 * list view file
 *
 * @project mvc
 * @author duong bien
 * @email bien.duongvan@yahoo.com
 * @date 16/7/2015
 * @time 11:41
 * @copyright 2015 Copyright duong bien
 * @license duong bien
 * @version 1.0.0
 */

?>
<div class="row">
    <div class="col-lg-12">
        <ul class="breadcrumb">
            <li><a href="<?php echo BASE_URL.'admin'?>">Quản trị</a></li>
            <li class="active"><?php $mbftext->__('Tra cứu thuê bao Blacklist'); ?></li>
        </ul>
    </div>
</div>

<div class="row ds-blacklist">

    <div class="col-lg-12">

        <form action="" name="filterForm" method="post" id="filterForm">
            <div class="col-lg-12">
                <div class="row">
                    <div class="panel panel-default">
                        <div class="panel-heading"><i class="fa fa-search"></i> Lọc dữ liệu
                            <div class="btn-group pull-right" id="dropdown-toggle">
                                <button class="btn btn-default btn-xs" type="button">
                                    <i class="fa fa-chevron-down"></i>
                                </button>
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-sm-4">
                                    <div class="form-group small">
                                        <label>Nhập số thuê bao</label>
                                        <input placeholder="918014988" onfocus="this.placeholder = ''" onblur="this.placeholder = '918014988'" class="form-control small" name="msisdn" id="msisdn" value="<?php if (isset($data['msisdn'])) : ?><?php echo $data['msisdn']; ?><?php endif; ?>" />
                                    </div>
                                </div>
                                <div class="col-sm-2">
                                    <div class="form-group small" style="margin-top: 20px;">
                                        <input type="hidden" name="task" value="filter" />
                                        <input class="btn btn-primary btn-sm" type="submit" value="Tra cứu" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>

        <?php if (count($data['collection']) < 1): ?>
            <p class="no-data"><?php echo "Không tìm thấy thuê bao " . $data['msisdn'] . " trong danh sách Blacklist"; ?></p>
            <?php if ((int)$data['return_value'] != 1): ?>
                <p class="error-mess"><?php echo "Mã kết quả trả về: " . $data['return_value']; ?></p>
                <p class="error-mess"><?php echo "Thông tin lỗi : " . $data['description']; ?></p>
            <?php endif; ?>
        <?php else: ?>
        <form action="" name="" method="post" id="MyForm">
            <div class="col-sm-12">
                <div class="row">
                    <table id="dataTables-example" class="table table-striped table-bordered table-hover dataTable">
                        <thead>
                        <tr>
                            <th style="width: 70px;"><?php $mbftext->__('Số thuê bao');?></th>
                            <th style="width: 70px;"><?php $mbftext->__('Ngày tạo');?></th>
                            <th style="width: 40px;"><?php $mbftext->__('Trạng thái');?></th>
                            <th style="width: 80px;"><?php $mbftext->__('Lý do'); ?></th>
                            <th style="width: 250px;"><?php $mbftext->__('Tên lý do'); ?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php $line = 0; ?>
                        <?php foreach ($data['collection'] as $entry): ?>
                            <?php
                            $class = "";
                            if (($line % 2) == 0) $class .= " even-line";
                            else $class .= " odd-line";
                            if ($line == 0) $class .= " first";
                            $line++;
                            ?>
                            <tr class="grade odd<?php echo $class; ?>">
                                <td><?php echo $entry['MSISDN']; ?></td>
                                <td><?php echo $entry['CREATE_DATE']; ?></td>
                                <td><?php ((int)$entry['STATUS'] == 1) ? $mbftext->__("Còn hiệu lực") : $mbftext->__("Hết hiệu lực"); ?></td>
                                <td><?php echo $entry['REASON_CODE']; ?></td>
                                <td><?php echo $entry['REASON_NAME']; ?></td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </form>
    </div>
    <?php endif;?>

</div>

<script type="text/javascript">

    $(document).ready(function() {
        $('#filterForm').validate({
            rules: {
                msisdn: {
                    required: true
                }
            },
            messages: {
                // Enter custom error text here.
            }
        });

    });

</script>