<?php

/**
* list.phtml
* 
* list view file
* 
* @project mvc 
* @author duong bien
* @email bien.duongvan@yahoo.com 
* @date 16/7/2015
* @time 11:41
* @copyright 2015 Copyright duong bien
* @license duong bien
* @version 1.0.0
*/

?>
<div class="row">
    <div class="col-lg-12">
        <ul class="breadcrumb">
            <li><a href="<?php echo BASE_URL.'admin'?>">Quản trị</a></li>
            <li class="active">Tra cứu giao dịch ứng thẻ</li>
        </ul>
    </div>
</div>

<div class="row">

    <div class="col-lg-12">
		
		<form action="" name="filterForm" method="post" id="filterForm">
            <div class="col-lg-12">
                <div class="row">
                    <div class="panel panel-default">
                        <div class="panel-heading"><i class="fa fa-search"></i> Lọc dữ liệu
                            <div class="btn-group pull-right" id="dropdown-toggle">
                                <button class="btn btn-default btn-xs" type="button">
                                    <i class="fa fa-chevron-down"></i>
                                </button>
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-sm-3">
                                    <div class="form-group small">
                                        <label>Nhập số điện thoại</label>
                                        <input placeholder="918014988" onfocus="this.placeholder = ''" onblur="this.placeholder = '918014988'" class="form-control small" name="msisdn" id="msisdn" value="<?php if (isset($data['msisdn'])) : ?><?php echo $data['msisdn']; ?><?php endif; ?>" />
                                    </div>
                                </div>
								<div class="col-sm-3">
                                    <div class="form-group small">
                                        <label>Từ ngày</label>
                                        <input class="form-control small" name="f_date" id="f_date"
                                               value="<?php if (isset($data['f_date'])) : ?><?php echo date("d-m-Y", strtotime($data['f_date'])); ?><?php endif; ?>"/>
                                    </div>
                                </div>
                                <div class="col-sm-3">
                                    <div class="form-group small">
                                        <label>Đến ngày</label>
                                        <input class="form-control small" name="t_date" id="t_date"
                                               value="<?php if (isset($data['t_date'])) : ?><?php echo date("d-m-Y", strtotime($data['t_date'])); ?><?php endif; ?>"/>
                                    </div>
                                </div>
                                <div class="col-sm-2">
                                    <div class="form-group small" style="margin-top: 20px;">
                                        <input type="hidden" name="task" value="filter" />
										<input class="btn btn-primary btn-sm" type="submit" value="Tra cứu" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>

        <?php if(empty($data['collection'])):?>
            <p class="no-data"><?php echo NODATA;?></p>
            <?php if((int)$data['return_value'] != 1):?>
                <p class="error-mess"><?php echo "Mã kết quả trả về: ". $data['return_value'];?></p>
                <p class="error-mess"><?php echo "Thông tin lỗi : ". $data['description'];?></p>
            <?php endif; ?>
        <?php else:?>

        <form action="" name="" method="post" id="MyForm">
            <p class="success-mess">Tổng số <?php echo count($data['collection']); ?> bản ghi được tìm thấy.</p>
            <div class="col-sm-12">
                <div class="row">
                    <table id="dataTables-example" class="table table-striped table-bordered table-hover dataTable">
                        <thead>
                            <tr>
                                <th><?php $mbftext->__('Mã giao dịch');?></th>
                                <th><?php $mbftext->__('Mã thuê bao');?></th>
								<th><?php $mbftext->__('Số thuê bao');?></th>
								<th><?php $mbftext->__('Mệnh giá');?></th>
								<th style="min-width:150px;"><?php $mbftext->__('Serial');?></th>
								<th style="min-width:100px;"><?php $mbftext->__('Ngày giao dịch');?></th>
								<th><?php $mbftext->__('Nguồn ứng');?></th>
								<th><?php $mbftext->__('Trạng thái');?></th>
								<th><?php $mbftext->__('Trạng thái MT');?></th>
								<th><?php $mbftext->__('Trạng thái giao dịch');?></th>
								<th><?php $mbftext->__('Mã lỗi');?></th>
                                <th><?php $mbftext->__('SMS gửi khách hàng');?></th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php $line = 0; ?>
                        <?php foreach ($data['collection'] as $entry): ?>
                            <?php
                            $class = "";
                            if (($line % 2) == 0) $class .= " even-line";
                            else $class .= " odd-line";
                            if ($line == 0) $class .= " first";
                            $line++;
                            ?>
                            <tr class="grade odd<?php echo $class; ?>">
                                <td><?php echo $entry['CREDIT_TRANS_ID']?></td>
                                <td><?php echo $entry['SUB_ID']?></td>
                                <td><?php echo $entry['MSISDN']?></td>
                                <td><?php echo number_format($entry['CARD_AMOUNT'])?><sub class="vnd">đ</sub></td>
                                <td><?php echo ($entry['CARD_SERIAL'] == null) ? 'Null' : $entry['CARD_SERIAL'];?></td>
                                <td><?php echo $entry['TRANS_DATE'] ?></td>
                                <td><?php echo ($entry['REQUEST_SOURCE'] == 0) ? 'SMS' : 'USD';?></td>
                                <td><?php echo ($entry['CONDITION_STATUS'] == 1) ? '<span style="color: green;">'.$mbftext->__('Đủ điều kiện').'</span>' : '<span style="color: red;">'.$mbftext->__('Không đủ điều kiện').'</span>';?></td>
                                <td><?php
                                    if($entry['MT_STATUS'] == 0):
                                        echo $mbftext->__("Trong Queue");
                                    elseif($entry['MT_STATUS'] == 1):
                                        echo $mbftext->__("Đã gửi đến SMSC");
                                    elseif($entry['MT_STATUS'] == 2):
                                        echo $mbftext->__("Thuê bao đã nhận dc MT");
                                    elseif($entry['MT_STATUS'] == 3):
                                        echo $mbftext->__("TB không nhận dc MT");
                                    else:
                                        echo $mbftext->__("Unknown");
                                    endif;

                                    ?></td>
                                <td><?php echo ($entry['STATUS'] == 0) ? '<span style="color: red;">'.$mbftext->__('Lỗi').'</span>' : '<span style="color: green;">'.$mbftext->__('Thành công').'</span>'?></td>
                                <td><?php echo $entry['ERROR_CODE']?></td>
                                <td><?php echo $entry['MT_SMS']?></td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </form>
    </div>
    <?php endif;?>

</div>

<script type="text/javascript">

$(document).ready(function() {
    $('#filterForm').validate({
		rules: {
			msisdn: {
				required: true
			}
	    },
	    messages: {
	    	// Enter custom error text here.
		}
	});
	
	$("#f_date").datepicker({
		dateFormat: 'dd-mm-yy',
		showAnim: 'slideDown',
		onSelect: function (selected) {
			$("#t_date").datepicker("option", "minDate", selected)
		}
	});

	$("#t_date").datepicker({
		dateFormat: 'dd-mm-yy',
		showAnim: 'slideDown',
		onSelect: function (selected) {
			$("#f_date").datepicker("option", "maxDate", selected)
		}
	});
    
});

</script>