<?php

/**
 * list.phtml
 *
 * list view file
 *
 * @project mvc
 * @author duong bien
 * @email bien.duongvan@yahoo.com
 * @date 16/7/2015
 * @time 11:41
 * @copyright 2015 Copyright duong bien
 * @license duong bien
 * @version 1.0.0
 */

?>
<div class="row">
    <div class="col-lg-12">
        <ul class="breadcrumb">
            <li><a href="<?php echo BASE_URL . 'admin' ?>">Quản trị</a></li>
            <li class="active"><?php echo $mbftext->__('Tra cứu giao dịch hoàn ứng'); ?></li>
        </ul>
    </div>
</div>

<div class="row">

    <div class="col-lg-12">

        <form action="" name="filterForm" method="post" id="filterForm">
            <div class="col-lg-12">
                <div class="row">
                    <div class="panel panel-default">
                        <div class="panel-heading"><i class="fa fa-search"></i> Lọc dữ liệu
                            <div class="btn-group pull-right" id="dropdown-toggle">
                                <button class="btn btn-default btn-xs" type="button">
                                    <i class="fa fa-chevron-down"></i>
                                </button>
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-sm-3">
                                    <div class="form-group small">
                                        <label>Nhập số điện thoại</label>
                                        <input placeholder="918014988" onfocus="this.placeholder = ''"
                                               onblur="this.placeholder = '918014988'" class="form-control small"
                                               name="msisdn" id="msisdn"
                                               value="<?php if (isset($data['msisdn'])) : ?><?php echo $data['msisdn']; ?><?php endif; ?>"/>
                                    </div>
                                </div>
                                <div class="col-sm-3">
                                    <div class="form-group small">
                                        <label>Từ ngày</label>
                                        <input class="form-control small" name="f_date" id="f_date"
                                               value="<?php if (isset($data['f_date'])) : ?><?php echo $data['f_date']; ?><?php endif; ?>"/>
                                    </div>
                                </div>
                                <div class="col-sm-3">
                                    <div class="form-group small">
                                        <label>Đến ngày</label>
                                        <input class="form-control small" name="t_date" id="t_date"
                                               value="<?php if (isset($data['t_date'])) : ?><?php echo $data['t_date']; ?><?php endif; ?>"/>
                                    </div>
                                </div>
                                <div class="col-sm-2">
                                    <div class="form-group small" style="margin-top: 20px;">
                                        <input type="hidden" name="task" value="filter"/>
                                        <input class="btn btn-primary btn-sm" type="submit" value="Tra cứu"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>

        <?php if (count($data['collection']) < 1): ?>
            <p class="no-data empty-data"><?php echo NODATA; ?></p>
            <?php if ((int)$data['return_value'] != 1 && !empty($data['msisdn'])): ?>
                <p class="error-mess"><?php echo "Mã kết quả trả về: " . $data['return_value']; ?></p>
                <p class="error-mess"><?php echo "Thông tin lỗi : " ; $mbftext->__($data['description']); ?></p>
            <?php endif; ?>
        <?php else: ?>

        <?php //print_r($data['curs']);?>
        <form action="" name="" method="post" id="MyForm">
            <p class="success-mess">Tổng số <?php echo count($data['collection']); ?> bản ghi được tìm thấy.</p>
            <div class="col-sm-12">
                <div class="row">
                    <table id="dataTables-example" class="table table-striped table-bordered table-hover dataTable">
                        <thead>
                        <tr>
                            <th><?php $mbftext->__("Mã giao dịch hoàn ứng"); ?></th>
                            <th><?php $mbftext->__("Mã giao dịch ứng"); ?></th>
                            <th><?php $mbftext->__("Mã nợ"); ?></th>
                            <th><?php $mbftext->__("Mã thuê bao"); ?></th>
                            <th><?php $mbftext->__("Số thuê bao"); ?></th>
                            <th><?php $mbftext->__("Số tiền nạp"); ?></th>
                            <th style="min-width:60px;"><?php $mbftext->__("Số tiền đã hoàn ứng"); ?></th>
                            <th style="min-width: 100px;"><?php $mbftext->__("Hạn hoàn ứng"); ?></th>
                            <th><?php $mbftext->__("Nợ xấu"); ?></th>
                            <th><?php $mbftext->__("SMS gửi KH"); ?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr class="grade odd">

                        </tr>
                        </tbody>
                        <tbody>
                        <?php $line = 0; ?>
                        <?php foreach ($data['collection'] as $entry): ?>
                            <?php
                            $class = "";
                            if (($line % 2) == 0) $class .= " even-line";
                            else $class .= " odd-line";
                            if ($line == 0) $class .= " first";
                            $line++;
                            ?>
                            <tr class="grade odd<?php echo $class; ?>">
                                <td><?php echo $entry['PAYMENT_TRANS_ID']; ?></td>
                                <td><?php echo $entry['CREDIT_TRANS_ID'] ?></td>
                                <td><?php echo $entry['SUBS_DEBT_ID'] ?></td>
                                <td><?php echo $entry['SUB_ID'] ?></td>
                                <td><?php echo $entry['MSISDN'] ?></td>
                                <td><?php echo number_format($entry['RECHARGE_CARD_AMOUNT']) ?><sub
                                            class="vnd">đ</sub></td>
                                <td><?php echo number_format($entry['PAYMENT_CARD_AMOUNT'] + $entry['PAYMENT_FEE_AMOUNT']) ?>
                                    <sub class="vnd">đ</sub></td>
                                <td><?php echo date('d-m-Y H:i:s', strtotime($entry['PAYMENT_DATE'])) ?></td>
                                <td><?php echo ($entry['BAD_DEBT'] == 0) ? $mbftext->__('Nợ trong kỳ đối soát') : $mbftext->__('Nợ xấu không đối soát'); ?></td>
                                <td><?php echo $entry['SMS'] ?></td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </form>
    </div>
    <?php endif; ?>

</div>

<script type="text/javascript">

    $(document).ready(function () {
        $('#filterForm').validate({
            rules: {
                msisdn: {
                    required: true
                }
            },
            messages: {
                // Enter custom error text here.
            }
        });

        $("#f_date").datepicker({
            dateFormat: 'dd-mm-yy',
            showAnim: 'slideDown',
            onSelect: function (selected) {
                $("#t_date").datepicker("option", "minDate", selected)
            }
        });

        $("#t_date").datepicker({
            dateFormat: 'dd-mm-yy',
            showAnim: 'slideDown',
            onSelect: function (selected) {
                $("#f_date").datepicker("option", "maxDate", selected)
            }
        });

    });

</script>