<?php

/**
* list.phtml
* 
* list view file
* 
* @project mvc 
* @author duong bien
* @email bien.duongvan@yahoo.com 
* @date 16/7/2015
* @time 11:41
* @copyright 2015 Copyright duong bien
* @license duong bien
* @version 1.0.0
*/

?>
<div class="row">
    <div class="col-lg-12">
        <ul class="breadcrumb">
            <li><a href="<?php echo BASE_URL.'admin'?>">Quản trị</a></li>
            <li class="active">Tra cứu giao dịch ứng thẻ</li>
        </ul>
    </div>
</div>

<div class="row">

    <div class="col-lg-12">
		
		<form action="" name="filterForm" method="post" id="filterForm">
            <div class="col-lg-12">
                <div class="row">
                    <div class="panel panel-default">
                        <div class="panel-heading"><i class="fa fa-search"></i> Lọc dữ liệu
                            <div class="btn-group pull-right" id="dropdown-toggle">
                                <button class="btn btn-default btn-xs" type="button">
                                    <i class="fa fa-chevron-down"></i>
                                </button>
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-sm-3">
                                    <div class="form-group small">
                                        <label>Nhập số điện thoại</label>
                                        <input placeholder="918014988" onfocus="this.placeholder = ''" onblur="this.placeholder = '918014988'" class="form-control small" name="msisdn" id="msisdn" value="<?php if (isset($data['msisdn'])) : ?><?php echo $data['msisdn']; ?><?php endif; ?>" />
                                    </div>
                                </div>
								<div class="col-sm-3">
                                    <div class="form-group small">
                                        <label>Từ ngày</label>
                                        <input class="form-control small" name="f_date" id="f_date"
                                               value="<?php if (isset($data['f_date'])) : ?><?php echo date("d-m-Y", strtotime($data['f_date'])); ?><?php endif; ?>"/>
                                    </div>
                                </div>
                                <div class="col-sm-3">
                                    <div class="form-group small">
                                        <label>Đến ngày</label>
                                        <input class="form-control small" name="t_date" id="t_date"
                                               value="<?php if (isset($data['t_date'])) : ?><?php echo date("d-m-Y", strtotime($data['t_date'])); ?><?php endif; ?>"/>
                                    </div>
                                </div>
                                <div class="col-sm-2">
                                    <div class="form-group small" style="margin-top: 20px;">
                                        <input type="hidden" name="task" value="filter" />
										<input class="btn btn-primary btn-sm" type="submit" value="Tra cứu" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
		
        <?php if($data['curs'] == null):?>
            <p class="no-data"><?php echo NODATA;?></p>
        <?php else:?>

        <form action="" name="" method="post" id="MyForm">
            <div class="col-sm-12">
                <div class="row">
                    <table id="dataTables-example" class="table table-striped table-bordered table-hover dataTable">
                        <thead>
                            <tr>
                                <th class="text-center">Mã giao dịch</th>
								<th class="text-center">Mã thuê bao</th>
								<th class="text-center">Thuê bao</th>
								<th class="text-center">Mệnh giá thẻ</th>
								<th class="text-center" style="min-width:150px;">Serial</th>
								<th class="text-center">Ngày giao dịch</th>
								<th class="text-center">Nguồn ứng</th>
								<th class="text-center">Trạng thái</th>
								<th class="text-center">Trạng thái MT</th>
								<th class="text-center">Trạng thái giao dịch</th>
								<th class="text-center">Mã lỗi</th>
                                <th class="text-center">SMS gửi khách hàng</th>
                            </tr>
                        </thead>
                        <tbody>
							<tr class="grade odd">
								<?php $row = $data['curs'];?>
								<td class="text-center"><?php echo $row->CREDIT_TRANS_ID?></td>
								<td class="text-center"><?php echo $row->SUB_ID?></td>
								<td class="text-center"><?php echo $row->MSISDN?></td>
								<td class="text-center"><?php echo number_format($row->CARD_AMOUNT)?><sub class="vnd">đ</sub></td>
								<td class="text-center"><?php echo ($row->CARD_SERIAL == null) ? 'Null' : $row->CARD_SERIAL;?></td>
								<td class="text-center"><?php echo $row->TRANS_DATE ?></td>
								<td class="text-center"><?php echo ($row->REQUEST_SOURCE == 0) ? 'SMS' : 'USD';?></td>
								<td class="text-center"><?php echo ($row->CONDITION_STATUS == 1) ? '<span style="color: green;">Đủ điều kiện</span>' : '<span style="color: red;">Không đủ điều kiện</span>';?></td>
								<td class="text-center"><?php 
									if($row->MT_STATUS == 0):
										echo "Trong Queue";
									elseif($row->MT_STATUS == 1):
										echo "Đã gửi đến SMSC";
									elseif($row->MT_STATUS == 2):
										echo "Thuê bao đã nhận dc MT";
									elseif($row->MT_STATUS == 3):
										echo "TB không nhận dc MT";
									else:
										echo "Unknown";
									endif;
									
								?></td>
								<td class="text-center"><?php echo ($row->STATUS == 0) ? '<span style="color: red;">Lỗi</span>' : '<span style="color: green;">Thành công</span>'?></td>
								<td class="text-center"><?php echo $row->ERROR_CODE?></td>
                                <td class="text-center"><?php echo $row->MT_SMS?></td>
							</tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </form>
    </div>
    <?php endif;?>

</div>

<script type="text/javascript">

$(document).ready(function() {
    $('#filterForm').validate({
		rules: {
			msisdn: {
				required: true
			}
	    },
	    messages: {
	    	// Enter custom error text here.
		}
	});
	
	$("#f_date").datepicker({
		dateFormat: 'dd-mm-yy',
		showAnim: 'slideDown',
		onSelect: function (selected) {
			$("#t_date").datepicker("option", "minDate", selected)
		}
	});

	$("#t_date").datepicker({
		dateFormat: 'dd-mm-yy',
		showAnim: 'slideDown',
		onSelect: function (selected) {
			$("#f_date").datepicker("option", "maxDate", selected)
		}
	});
    
});

</script>