<?php

/**
 * list.phtml
 *
 * list view file
 *
 * @project mvc
 * @author duong bien
 * @email bien.duongvan@yahoo.com
 * @date 16/7/2015
 * @time 11:41
 * @copyright 2015 Copyright duong bien
 * @license duong bien
 * @version 1.0.0
 */

?>
<div class="row">
    <div class="col-lg-12">
        <ul class="breadcrumb">
            <li><a href="<?php echo BASE_URL . 'admin' ?>">Quản trị</a></li>
            <li class="active"><?php echo $title;?></li>
        </ul>
    </div>
</div>

<div class="row">

    <div class="col-lg-12">

        <form action="" name="filterForm" method="post" id="filterForm">
            <div class="col-lg-12">
                <div class="row">
                    <div class="panel panel-default">
                        <div class="panel-heading"><i class="fa fa-search"></i> Lọc dữ liệu
                            <div class="btn-group pull-right" id="dropdown-toggle">
                                <button class="btn btn-default btn-xs" type="button">
                                    <i class="fa fa-chevron-down"></i>
                                </button>
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-sm-3">
                                    <div class="form-group small">
                                        <label>Số điện thoại(thêm đầu 84)</label>
                                        <input placeholder="84918014988" onfocus="this.placeholder = ''"
                                               onblur="this.placeholder = '84918014988'" class="form-control small"
                                               name="_msisdn" id="_msisdn"
                                               value="<?php if (isset($data['msisdn'])) : ?><?php echo $data['msisdn']; ?><?php endif; ?>"/>
                                    </div>
                                </div>
                                <div class="col-sm-2">
                                    <div class="form-group small">
                                        <label>Mã giao dịch</label>
                                        <input class="form-control small"
                                               name="_requestid" id="_requestid"
                                               value="<?php if (isset($data['_requestid'])) : ?><?php echo $data['_requestid']; ?><?php endif; ?>"/>
                                    </div>
                                </div>

                                <div class="col-sm-2">
                                    <div class="form-group small">
                                        <label>Từ ngày</label>
                                        <input class="form-control small" name="f_date" id="f_date"
                                               placeholder="01/02/2017" onfocus="this.placeholder = ''"
                                               onblur="this.placeholder = '01/02/2017'"
                                               value="<?php if (isset($data['f_date'])) : ?><?php echo $data['f_date']; ?><?php endif; ?>"/>
                                    </div>
                                </div>
                                <div class="col-sm-2">
                                    <div class="form-group small">
                                        <label>Đến ngày</label>
                                        <input class="form-control small" name="t_date" id="t_date"
                                               placeholder="01/02/2017" onfocus="this.placeholder = ''"
                                               onblur="this.placeholder = '01/02/2017'"
                                               value="<?php if (isset($data['t_date'])) : ?><?php echo $data['t_date']; ?><?php endif; ?>"/>
                                    </div>
                                </div>
                                <div class="col-sm-2">
                                    <div class="form-group small" style="margin-top: 20px;">
                                        <input type="hidden" name="task" value="filter"/>
                                        <input class="btn btn-primary btn-sm" type="submit" value="Tra cứu"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>

        <?php if (count($data['collection']) < 1): ?>
            <p class="no-data empty-data"><?php echo NODATA; ?></p>
            <?php if ((int)$data['return_value'] != 1 && !empty($data['msisdn'])): ?>
                <p class="error-mess"><?php echo "Mã kết quả trả về: " . $data['return_value']; ?></p>
                <p class="error-mess"><?php echo "Thông tin lỗi : ";
                    $mbftext->__($data['description']); ?></p>
            <?php endif; ?>
        <?php else: ?>

        <form action="" name="" method="post" id="MyForm">
            <p class="success-mess">Tổng số <?php echo count($data['collection']); ?> bản ghi được tìm thấy.</p>
            <p class="error-mess"></p>
            <div class="col-sm-12">
                <div class="row">
                    <table id="dataTables-example" class="table table-striped table-bordered table-hover dataTable">
                        <thead>
                        <tr>
                            <th><?php $mbftext->__('Mã giao dịch'); ?></th>
                            <th><?php $mbftext->__('Số thuê bao'); ?></th>
                            <th><?php $mbftext->__('Nội dung'); ?></th>
                            <th><?php $mbftext->__('Trạng thái gửi tin nhắn'); ?></th>
                            <th><?php $mbftext->__('Thời gian gửi tin nhắn'); ?></th>
                            <th><?php $mbftext->__('Trạng thái delivery report'); ?></th>
                            <th><?php $mbftext->__('Thời gian nhận delivery report'); ?></th>
                            <th><?php $mbftext->__('Thời gian nhận request'); ?></th>
                            <th><?php $mbftext->__('Thời gian cập nhật cuối cùng'); ?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php $line = 0; ?>
                        <?php foreach ($data['collection'] as $entry): ?>
                            <?php
                            $class = "";
                            if (($line % 2) == 0) $class .= " even-line";
                            else $class .= " odd-line";
                            if ($line == 0) $class .= " first";
                            $line++;
                            ?>
                            <?php
                                $SUBMIT_STATUS = "";
                            switch ($entry['SUBMIT_STATUS']) {
                                case '0':
                                    $SUBMIT_STATUS = "Gửi tin nhắn thành công";
                                    break;
                                case '104':
                                    $SUBMIT_STATUS = "Gửi tin nhắn thất bại";
                                    break;
                                default:
                                    $SUBMIT_STATUS = "Không rõ mã:".$entry['SUBMIT_STATUS'];
                            }
                            ?>
                            <?php
                            $DELIVERY_REPORT_STATUS = "";
                            switch ($entry['DELIVERY_REPORT_STATUS']) {
                                case '1':
                                    $DELIVERY_REPORT_STATUS = "Gửi thành công";
                                    break;
                                case '2':
                                    $DELIVERY_REPORT_STATUS = "Gửi thất bại";
                                    break;
                                case '3':
                                    $DELIVERY_REPORT_STATUS = "KEEP-RETRYING";
                                    break;
                                case '4':
                                    $DELIVERY_REPORT_STATUS = "Đang gửi";
                                    break;
                                case '5':
                                    $DELIVERY_REPORT_STATUS = "Không xác định";
                                    break;
                                default:
                                    $DELIVERY_REPORT_STATUS = "Không rõ mã:".$entry['DELIVERY_REPORT_STATUS'];
                            }
                            ?>

                            <tr class="grade odd<?php echo $class; ?>">
                                <td><?php echo $entry['REQUEST_ID'] ?></td>
                                <td><?php echo $entry['MSISDN'] ?></td>
                                <td><?php echo $entry['CONTENT'] ?></td>
                                <td><?php echo $SUBMIT_STATUS ?></td>
                                <td><?php echo $entry['SUBMIT_TIME'] ?></td>
                                <td><?php echo $DELIVERY_REPORT_STATUS ?></td>
                                <td><?php echo $entry['DELIVERY_REPORT_TIME'] ?></td>
                                <td><?php echo $entry['INSERT_TIME'] ?></td>
                                <td><?php echo $entry['LAST_UPDATE_TIME'] ?></td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </form>
    </div>
    <?php endif; ?>

</div>