<?php

/**
* list.phtml
* 
* list view file
* 
* @project mvc 
* @author duong bien
* @email bien.duongvan@yahoo.com 
* @date 16/7/2015
* @time 11:41
* @copyright 2015 Copyright duong bien
* @license duong bien
* @version 1.0.0
*/

?>
<div class="row">
    <div class="col-lg-12">
        <ul class="breadcrumb">
            <li><a href="<?php echo BASE_URL.'admin'?>"><?php echo $mbftext->__('Quản trị'); ?></a></li>
            <li class="active"><?php echo $mbftext->__('Tra cứu nợ'); ?></li>
        </ul>
    </div>
</div>

<div class="row">

    <div class="col-lg-12">
		
		<form action="" name="filterForm" method="post" id="filterForm">
            <div class="col-lg-12">
                <div class="row">
                    <div class="panel panel-default">
                        <div class="panel-heading"><i class="fa fa-search"></i> Lọc dữ liệu
                            <div class="btn-group pull-right" id="dropdown-toggle">
                                <button class="btn btn-default btn-xs" type="button">
                                    <i class="fa fa-chevron-down"></i>
                                </button>
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-sm-4">
                                    <div class="form-group small">
                                        <label>Nhập số điện thoại</label>
                                        <input placeholder="918014988" onfocus="this.placeholder = ''" onblur="this.placeholder = '918014988'" class="form-control small" name="msisdn" id="msisdn" value="<?php if (isset($data['msisdn'])) : ?><?php echo $data['msisdn']; ?><?php endif; ?>" />
                                    </div>
                                </div>
                                <div class="col-sm-2">
                                    <div class="form-group small" style="margin-top: 20px;">
                                        <input type="hidden" name="task" value="filter" />
										<input class="btn btn-primary btn-sm" type="submit" value="Tra cứu" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
		
        <?php if($data['curs'] == null):?>
            <p class="no-data"><?php echo NODATA;?></p>
        <?php else:?>
		<?php //print_r($data['curs']);?>
        <form action="" name="" method="post" id="MyForm">
            <div class="col-sm-12">
                <div class="row">
                    <table id="dataTables-example" class="table table-striped table-bordered table-hover dataTable">
                        <thead>
                            <tr>
                                <th class="text-center"><?php echo $mbftext->__('Mã nợ'); ?></th>
								<th class="text-center"><?php echo $mbftext->__('Mã giao dịch ứng'); ?></th>
								<th class="text-center"><?php echo $mbftext->__('Mã thuê bao'); ?></th>
								<th class="text-center"><?php echo $mbftext->__('Số thuê bao'); ?></th>
								<th class="text-center"><?php echo $mbftext->__('Nợ ban đầu'); ?></th>
								<th class="text-center"><?php echo $mbftext->__('Nợ hiện tại'); ?></th>
								<th class="text-center"><?php echo $mbftext->__('Ngày GD thanh toán cuối cùng'); ?></th>
								<th class="text-center"><?php echo $mbftext->__('Hạn Thanh toán'); ?></th>
								<th class="text-center"><?php echo $mbftext->__('Thời hạn hoàn ứng chính thẻ đã ứng'); ?></th>
								<th class="text-center"><?php echo $mbftext->__('Trạng thái nợ'); ?></th>
                            </tr>
                        </thead>
                        <tbody>
                        <tr class="grade odd">
							<?php $row = $data['curs'];?>
							<td class="text-center"><?php echo $row->SUBS_DEBT_ID?></td>
							<td class="text-center"><?php echo $row->CREDIT_TRANS_ID?></td>
							<td class="text-center"><?php echo $row->SUB_ID?></td>
							<td class="text-center"><?php echo $row->MSISDN?></td>
							<td class="text-center"><?php echo number_format($row->ORIGINAL_CARD_DEBT + $row->ORIGINAL_FEE_DEBT)?><sub class="vnd">đ</sub></td>
							<td class="text-center" style="width:150px;"><?php echo number_format($row->CURRENT_CARD_DEBT + $row->CURRENT_FEE_DEBT)?><sub class="vnd">đ</sub></td>
							<td class="text-center" style="width:150px;"><?php echo ($row->LAST_PAYMENT_DATE == null) ? "Null" : date('d-m-Y H:i:s', strtotime($row->LAST_PAYMENT_DATE));?></td>
							<td class="text-center" style="width:150px;"><?php echo date('d-m-Y H:i:s', strtotime($row->PAYMENT_DEADLINE))?></td>
							<td class="text-center" style="width:150px;"><?php echo date('d-m-Y H:i:s', strtotime($row->LIMIT_CARD_USING_TIME))?></td>
							<td class="text-center"><?php 
								if($row->DEBT_STATUS == 0):
									echo $mbftext->__("Nợ tạm");
								elseif($row->DEBT_STATUS == 1):
									echo $mbftext->__("Nợ chính thức");
								elseif($row->DEBT_STATUS == 2):
									echo $mbftext->__("Nợ bị xóa khi không nhận dc mã thẻ");
								elseif($row->DEBT_STATUS == 3):
									echo $mbftext->__("Nợ bị xóa khi thuê bao đã cắt hủy");
								else:
									echo $mbftext->__("Unknown");
								endif;
								
							?></td>
						</tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </form>
    </div>
    <?php endif;?>

</div>

<script type="text/javascript">

$(document).ready(function() {
    $('#filterForm').validate({
		rules: {
			msisdn: {
				required: true
			}
	    },
	    messages: {
	    	// Enter custom error text here.
		}
	});
});

</script>