<?php

/**
* list.phtml
* 
* list view file
* 
* @project mvc 
* @author duong bien
* @email bien.duongvan@yahoo.com 
* @date 16/7/2015
* @time 11:41
* @copyright 2015 Copyright duong bien
* @license duong bien
* @version 1.0.0
*/

?>
<div class="row">
    <div class="col-lg-12">
        <ul class="breadcrumb">
            <li><a href="<?php echo BASE_URL.'admin'?>"><?php $mbftext->__('Quản trị'); ?></a></li>
            <li class="active"><?php $mbftext->__('Tra cứu nợ'); ?></li>
        </ul>
    </div>
</div>

<div class="row">

    <div class="col-lg-12">
		
		<form action="" name="filterForm" method="post" id="filterForm">
            <div class="col-lg-12">
                <div class="row">
                    <div class="panel panel-default">
                        <div class="panel-heading"><i class="fa fa-search"></i> Lọc dữ liệu
                            <div class="btn-group pull-right" id="dropdown-toggle">
                                <button class="btn btn-default btn-xs" type="button">
                                    <i class="fa fa-chevron-down"></i>
                                </button>
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-sm-4">
                                    <div class="form-group small">
                                        <label>Nhập số điện thoại</label>
                                        <input placeholder="918014988" onfocus="this.placeholder = ''" onblur="this.placeholder = '918014988'" class="form-control small" name="msisdn" id="msisdn" value="<?php if (isset($data['msisdn'])) : ?><?php echo $data['msisdn']; ?><?php endif; ?>" />
                                    </div>
                                </div>
                                <div class="col-sm-2">
                                    <div class="form-group small" style="margin-top: 20px;">
                                        <input type="hidden" name="task" value="filter" />
										<input class="btn btn-primary btn-sm" type="submit" value="Tra cứu" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>

        <?php if(count($data['collection']) < 1):?>
            <p class="no-data"><?php echo NODATA;?></p>
            <?php if((int)$data['return_value'] != 1):?>
                <p class="error-mess"><?php echo "Mã kết quả trả về: ". $data['return_value'];?></p>
                <p class="error-mess"><?php echo "Thông tin lỗi : ". $data['description'];?></p>
            <?php endif; ?>
        <?php else:?>
        <form action="" name="" method="post" id="MyForm">
            <div class="col-sm-12">
                <div class="row">
                    <table id="dataTables-example" class="table table-striped table-bordered table-hover dataTable">
                        <thead>
                            <tr>
                                <th class="text-center"><?php $mbftext->__('Mã nợ'); ?></th>
								<th class="text-center"><?php $mbftext->__('Mã giao dịch ứng'); ?></th>
								<th class="text-center"><?php $mbftext->__('Mã thuê bao'); ?></th>
								<th class="text-center"><?php $mbftext->__('Số thuê bao'); ?></th>
								<th class="text-center"><?php $mbftext->__('Nợ ban đầu'); ?></th>
								<th class="text-center"><?php $mbftext->__('Nợ hiện tại'); ?></th>
								<th class="text-center"><?php $mbftext->__('Ngày GD thanh toán cuối cùng'); ?></th>
								<th class="text-center"><?php $mbftext->__('Hạn Thanh toán'); ?></th>
								<th class="text-center"><?php $mbftext->__('Thời hạn hoàn ứng chính thẻ đã ứng'); ?></th>
								<th class="text-center"><?php $mbftext->__('Trạng thái nợ'); ?></th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                        <tbody>
                        <?php $line = 0; ?>
                        <?php foreach ($data['collection'] as $entry): ?>
                            <?php
                            $class = "";
                            if (($line % 2) == 0) $class .= " even-line";
                            else $class .= " odd-line";
                            if ($line == 0) $class .= " first";
                            $line++;
                            ?>
                            <tr class="grade odd<?php echo $class; ?>">
                                <td class="text-center"><?php echo $entry['SUBS_DEBT_ID'];?></td>
                                <td class="text-center"><?php echo $entry['CREDIT_TRANS_ID'];?></td>
                                <td class="text-center"><?php echo $entry['SUB_ID'];?></td>
                                <td class="text-center"><?php echo $entry['MSISDN'];?></td>
                                <td class="text-center"><?php echo number_format($entry['ORIGINAL_CARD_DEBT'] + $entry['ORIGINAL_FEE_DEBT'])?><sub class="vnd">đ</sub></td>
                                <td class="text-center" style="width:150px;"><?php echo number_format($entry['CURRENT_CARD_DEBT'] + $entry['CURRENT_FEE_DEBT'])?><sub class="vnd">đ</sub></td>
                                <td class="text-center" style="width:150px;"><?php echo ($entry['LAST_PAYMENT_DATE'] == null) ? "Null" : date('d-m-Y H:i:s', strtotime($entry['LAST_PAYMENT_DATE']));?></td>
                                <td class="text-center" style="width:150px;"><?php echo date('d-m-Y H:i:s', strtotime($entry['PAYMENT_DEADLINE']))?></td>
                                <td class="text-center" style="width:150px;"><?php echo date('d-m-Y H:i:s', strtotime($entry['LIMIT_CARD_USING_TIME']))?></td>
                                <td class="text-center"><?php
                                    if($entry['DEBT_STATUS'] == 0):
                                        $mbftext->__("Nợ tạm");
                                    elseif($entry['DEBT_STATUS'] == 1):
                                        $mbftext->__("Nợ chính thức");
                                    elseif($entry['DEBT_STATUS'] == 2):
                                        $mbftext->__("Nợ bị xóa khi không nhận dc mã thẻ");
                                    elseif($entry['DEBT_STATUS'] == 3):
                                        $mbftext->__("Nợ bị xóa khi thuê bao đã cắt hủy");
                                    else:
                                        $mbftext->__("Unknown");
                                    endif;

                                    ?></td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </form>
    </div>
    <?php endif;?>

</div>

<script type="text/javascript">

$(document).ready(function() {
    $('#filterForm').validate({
		rules: {
			msisdn: {
				required: true
			}
	    },
	    messages: {
	    	// Enter custom error text here.
		}
	});
});

</script>