<?php

/**
* add.phtml
* 
* add view file
* 
* @project mvc 
* @author duong bien
* @email bien.duongvan@yahoo.com 
* @date 16/7/2015
* @time 11:38
* @copyright 2015 Copyright duong bien
* @license duong bien
* @version 1.0.0
*/

?>
<div class="row">
    <div class="col-lg-12">
        <div class="row">
            <ul class="breadcrumb">
                <li><a href="<?php echo BASE_URL.'admin'?>">Quản trị</a></li>
                <li><a href="<?php echo BASE_URL.'user/list'?>">Danh sách người dùng</a></li>
                <li class="active">Thêm người dùng mới</li>
            </ul>
            <?php if(isset($message) && ($message != null)):?>
            <div class="alert alert-success alert-dismissable">
                <button aria-hidden="true" data-dismiss="alert" class="close" type="button">x</button>
                <?php echo $message;?>
            </div>
            <?php endif;?>
        </div>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
    <div class="panel panel-default">
        <div class="panel-heading">
            <i class="fa fa-edit fa-fw"></i> 
            Nhập các thông tin về người dùng vào form dưới đây:
        </div>
        <div class="panel-body">
            <form action="" id="addUserForm" method="post" enctype="multipart/form-data">
                <div class="col-lg-12">
                    <div class="row">
                        <div class="col-lg-8">
                            <div class="form-group">
                                <label>Tên đầy đủ</label>
                                <input class="form-control" type="text" name="full_name" id="full_name" />
                            </div>
                            <div class="form-group">
                                <label>Tên đăng nhập</label>
                                <input class="form-control" type="text" name="user_name" id="user_name" />
                            </div>
                            <div class="form-group">
                                <label>Mật khẩu</label>
                                <input class="form-control" type="password" name="password" id="password" />
                            </div>
                            <div class="form-group">
                                <label>Nhập lại mật khẩu</label>
                                <input class="form-control" type="password" name="repassword" id="repassword" />
                            </div>
                            <div class="form-group">
                                <label>Email</label>
                                <input class="form-control" type="email" name="email" id="email" />
                            </div> 
                            <?php if(count($groups)>0):?>
                            <div class="form-group">
                                <label>Nhóm</label>
                                <select class="form-control" name="group_id" id="group_id">
                                    <option value="">----</option>
                                    <?php foreach($groups as $row):?>
                                    <option value="<?php echo $row['GROUP_ID'];?>"><?php echo $row['GROUP_NAME'];?></option>
                                    <?php endforeach;?>
                                </select>
                            </div> 
                            <?php endif;?>
                            <div class="form-group">
                                <input class="btn btn-primary btn-sm" type="submit" value="Lưu" />
                            </div>                   
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script type="text/javascript">

$(document).ready(function() {
    $('#addUserForm').validate({
		rules: {
			full_name: {
				required: true
			},
			user_name: {
		  		required: true,
		  		minlength: 3,
		  		maxlength: 255,
		  		remote: '<?php echo BASE_URL.'user/check?check_type=user_name';?>'
			},
			email: {
				required: true,
				email: true,
				remote: '<?php echo BASE_URL.'user/check?check_type=email';?>'
			},
			password: {
		  		required: true,
		  		minlength: 3
			},
			repassword: {
				equalTo: '#password'
			},
	    },
	    messages: {
	    	// Enter custom error text here.
		}
	});
    
    $('#group_id').selectpicker({
          liveSearch: false,
          maxOptions: 1
    });
});

</script>