<?php

/**
* list.phtml
* 
* list view file
* 
* @project mvc 
* @author duong bien
* @email bien.duongvan@yahoo.com 
* @date 16/7/2015
* @time 11:41
* @copyright 2015 Copyright duong bien
* @license duong bien
* @version 1.0.0
*/

?>
<div class="row">
    <div class="col-lg-12">
        <ul class="breadcrumb">
            <li><a href="<?php echo BASE_URL.'admin'?>">Quản trị</a></li>
            <li class="active">Danh sách người dùng</li>
        </ul>
    </div>
</div>

<div class="row">

    <div class="col-lg-12">
        <?php if(count($users) == 0):?>
			<div class="col-sm-12 bottom-10">
                <div class="">
					<?php if($acl->allow("user","add")):?>
                    <a href="<?php echo BASE_URL.'user/add'?>" class="btn btn-primary btn-sm pull-right">Thêm người dùng</a>
					<?php endif;?>
                </div>
            </div>
            <p class="no-data"><?php echo NODATA;?></p>
        <?php else:?>
		<form action="" name="" method="post" id="filterForm">
            <div class="col-lg-12">
                <div class="row">
                    <div class="panel panel-default">
                        <div class="panel-heading"><i class="fa fa-search"></i> Lọc dữ liệu
                            <div class="btn-group pull-right" id="dropdown-toggle">
                                <button class="btn btn-default btn-xs" type="button">
                                    <i class="fa fa-chevron-down"></i>
                                </button>
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-sm-2">
                                    <div class="form-group small">
                                        <label>User Name</label>
                                        <input class="form-control small" name="user_name" id="user_name" value="<?php if (isset($exp['username'])) : ?><?php echo $exp['username']; ?><?php endif; ?>" />
                                    </div>
                                </div>
                                <div class="col-sm-2">
                                    <div class="form-group small">
                                        <label>Full Name</label>
                                        <input class="form-control small" name="full_name" id="full_name" value="<?php if (isset($exp['full_name'])) : ?><?php echo $exp['full_name']; ?><?php endif; ?>" />
                                    </div>
                                </div>
                                <div class="col-sm-2">
                                    <div class="form-group small">
                                        <label>Email</label>
                                        <input class="form-control small" name="email" id="email" value="<?php if (isset($exp['email'])) : ?><?php echo $exp['email']; ?><?php endif; ?>" />
                                    </div>
                                </div>
                                <div class="col-sm-2">
                                    <div class="form-group small">
                                        <label>Trạng thái</label>
                                        <select class="form-control small" name="status">
                                            <option value="" <?php if (!isset($exp['status'])) : ?> selected="selected"<?php endif; ?>>----</option>
                                            <option <?php if (isset($exp['status']) && $exp['status'] == 1) : ?> selected="selected"<?php endif; ?> value="1">Đã kích hoạt</option>
                                            <option <?php if (isset($exp['status']) && $exp['status'] == 0) : ?> selected="selected"<?php endif; ?> value="0">Chưa kích hoạt</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-sm-2">
                                    <div class="form-group small" style="margin-top: 20px;">
                                        <input type="hidden" name="task" value="filter" />
                                        <button class="btn btn-success btn-sm" type="submit">Lọc dữ liệu</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <form action="" name="" method="post" id="MyForm">
            
            <div class="col-sm-12 bottom-10">
                <div class="row">
					<?php if($acl->allow("user","add")):?>
                    <a href="<?php echo BASE_URL.'user/add'?>" class="btn btn-primary btn-sm pull-right">Thêm người dùng</a>
					<?php endif;?>
                    <?php if($acl->allow("user","delete")):?>
					<input onclick="gotoAction('delete','user');" type="submit" disabled="" id="delete" class="btn-action btn btn-danger btn-sm pull-right right-10" value="Xóa" />
                    <?php endif;?>
					<?php if($acl->allow("user","edit")):?>
					<input onclick="gotoAction('edit','user');" type="submit" disabled="" id="edit" class="btn-action btn btn-success btn-sm pull-right right-10"  value="Sửa" />
                    <?php endif;?>
					<?php if($acl->allow("user","activate")):?>
					<input onclick="gotoAction('status','user');" type="submit" disabled="" id="status" class="btn-action btn btn-warning btn-sm pull-right right-10" value="Đổi trạng thái" />
                    <?php endif;?>
					<?php if($acl->allow("permission","index")):?>
					<input onclick="gotoPermission('btn-permission','permission','user');" type="submit" disabled="" id="btn-permission" class="btn-action btn btn-primary btn-sm pull-right right-10" value="Quyền" />
                    <?php endif;?>
					<input type="hidden" name="task-list" value="submit" />
                </div>
            </div>
            <div class="col-sm-12">
                <div class="row">
                    <table id="dataTables-example" class="table table-striped table-bordered table-hover dataTable">
                        <thead>
                            <tr>
                                <th class="text-center" style="width:15px;"><input id="checkall" class="ids" onclick="checkAll('ids[]',this);" type="checkbox" /></th>
                                <?php if (Core_Login::getUserId() == ADMIN_ID):?>
								<th class="" style="width: 50px;">ID</th>
								<?php endif;?>
                                <th class="" style="width: 115px;">Username</th>
                                <th class="" style="width: 203px;">Full Name</th>
                                <th class="" style="width: 184px;">Email</th>
                                <th class="" style="width: 80px;">Nhóm</th>
                                <th class="text-center" style="width: 120px;">Trạng thái</th>
                            </tr>
                        </thead>
                        <tbody>

                        <?php foreach($users as $user):?>
                            <tr class="grade odd">
                                <td class="text-center"><input type="checkbox" id="ids" class="ids" value="<?php echo $user['USER_ID'];?>" name="ids[]" /></td>
                                <?php if (Core_Login::getUserId() == ADMIN_ID):?>
								<td class="text-center"><?php echo $user['USER_ID'];?></td>
								<?php endif;?>
                                <td><?php echo $user['USER_NAME'];?></td>
                                <td><?php echo $user['FULL_NAME'];?></td>
                                <td><?php echo $user['EMAIL'];?></td>
                                <td><?php echo $mdGroup->getGroupById($user['GROUP_ID'])->GROUP_NAME;?></td>
                                <td class="text-center"><?php echo ($user['IS_ACTIVE'] == 1) ? "<span class='isactive-color'>Đã kích hoạt</span>" : "<span class='inactive-color'>Chưa kích hoạt</span>";?></td>
                            </tr>
                            
                        <?php endforeach;?>
                        </tbody>
                    </table>
                </div>
            </div>
        </form>
        <div class="">
            <div class="col-sm-12">
                <div class="row">
                    <div class="dataTables_paginate paging_simple_numbers">
                    <?php echo $paging;?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php endif;?>

</div>
