<?php

/**
* list.phtml
* 
* list view file
* 
* @project mvc 
* @author duong bien
* @email bien.duongvan@yahoo.com 
* @date 16/7/2015
* @time 11:41
* @copyright 2015 Copyright duong bien
* @license duong bien
* @version 1.0.0
*/

?>
<div class="row">
    <div class="col-lg-12">
        <ul class="breadcrumb">
            <li><a href="<?php echo BASE_URL.'admin'?>">Quản trị</a></li>
            <li class="active">KPI MO</li>
        </ul>
    </div>
</div>

<div class="row">
    <div class="col-lg-12"> 

		<form action="" name="filterForm" method="post" id="filterForm">
            <div class="col-lg-12">
                <div class="row">
                    <div class="panel panel-default">
                        <div class="panel-heading"><i class="fa fa-search"></i> Lọc dữ liệu
                            <div class="btn-group pull-right" id="dropdown-toggle">
                                <button class="btn btn-default btn-xs" type="button">
                                    <i class="fa fa-chevron-down"></i>
                                </button>
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-sm-3">
                                    <div class="form-group small">
                                        <label>Từ ngày</label>
                                        <input class="form-control small" name="f_date" id="f_date"
                                               placeholder="01/02/2017" onfocus="this.placeholder = ''"
                                               onblur="this.placeholder = '01/02/2017'"
                                               value="<?php if (isset($data['f_date'])) : ?><?php echo $data['f_date']; ?><?php endif; ?>"/>
                                    </div>
								</div>
                                <div class="col-sm-3">
                                    <div class="form-group small">
                                        <label>Đến ngày</label>
                                        <input class="form-control small" name="t_date" id="t_date"
                                               placeholder="01/02/2017" onfocus="this.placeholder = ''"
                                               onblur="this.placeholder = '01/02/2017'"
                                               value="<?php if (isset($data['t_date'])) : ?><?php echo $data['t_date']; ?><?php endif; ?>"/>
                                    </div>
                                </div>
                                <div class="col-sm-2">
                                    <div class="form-group small" style="margin-top: 20px;">
                                        <input type="hidden" name="task" value="filter"/>
                                        <input class="btn btn-primary btn-sm" type="submit" value="Xem thống kê"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
		<?php if(count($kpi_mo) == 0):?>
		<p class="no-data"><?php echo NODATA;?></p>
		<?php else:?>
        <form action="" name="" method="post" id="MyForm">
            <div class="col-sm-12">
                <div class="row">
                    <table id="dataTables-example" class="table table-striped table-bordered table-hover dataTable">
                        <thead>
                            <tr>
                                <th class="text-center">Thời gian</th>
                                <th class="text-center">Số lượng MO</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php foreach($kpi_mo as $row):?>
                            <tr class="grade odd">
                                <td class="text-center"><?php echo date('d/m-Y', strtotime($row['DATE_CREATE']));?></td>
								<td class="text-center"><?php echo $row['COUNT']?></td>
                            </tr>
                        <?php endforeach;?>
                        </tbody>
					</table>
                </div>
            </div>
        </form>
		<?php endif;?>
    </div>

</div>
