<?php

/**
 * list.phtml
 *
 * list view file
 *
 * @project mvc
 * @author duong bien
 * @email bien.duongvan@yahoo.com
 * @date 16/7/2015
 * @time 11:41
 * @copyright 2015 Copyright duong bien
 * @license duong bien
 * @version 1.0.0
 */

?>
<div class="row">
    <div class="col-lg-12">
        <ul class="breadcrumb">
            <li><a href="<?php echo BASE_URL . 'admin' ?>">Quản trị</a></li>
            <li class="active">Báo cáo kho thẻ</li>
        </ul>
    </div>
</div>

<div class="row">

    <div class="col-lg-12">

        <?php if (count($data['collection']) < 1): ?>
            <p class="no-data empty-data"><?php echo NODATA; ?></p>
            <?php if (0): ?>
                <p class="error-mess"><?php echo "Mã kết quả trả về: " . $data['return_value']; ?></p>
                <p class="error-mess"><?php echo "Thông tin lỗi : ";
                    $mbftext->__($data['description']); ?></p>
            <?php endif; ?>
        <?php else: ?>

        <form action="" name="" method="post" id="MyForm">
            <div class="message-action">
                <div class="col-sm-7">
                    <?php $mbftext->renderFormMessage(count($data['collection']));?>
                </div>
                <!--<div class="col-sm-5">
                    <button id="tqexcel" type="button" onclick="export_tq_excel('#filterForm')">Xuất file Exel</button>
                    <button id="tqcsv" type="button">Xuất file Csv</button>
                </div>-->

            </div>
            <div class="col-sm-12">
                <div class="row">
                    <table id="dataTables-example" class="table table-striped table-bordered table-hover dataTable">
                        <thead>
                        <tr>
                            <th>Mệnh giá 10k</th>
                            <th>Mệnh giá 20k</th>
                            <th>Mệnh giá 30k</th>
                            <th>Mệnh giá 50k</th>
                            <th>Mệnh giá 100k</th>
                            <th>Mệnh giá 200k</th>
                            <th>Mệnh giá 500k</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php $line = 0;?>
                        <?php foreach ($data['collection'] as $entry): ?>
                            <?php
                            $class = "";
                            if (($line % 2) == 0) $class .= " even-line";
                            else $class .= " odd-line";
                            if ($line == 0) $class .= " first";
                            $line++;
                            $cards = $entry;

                            $ten = 0;
                            $twenty = 0;
                            $thirty = 0;
                            $fifty = 0;
                            $hundred = 0;
                            $twohun = 0;
                            $fivehun = 0;
                            foreach ($cards as $card){
                                $amount = $card['AMOUNT'];
                                switch ($amount) {
                                    case '10000':
                                        $ten = $card['NUM'];
                                        break;
                                    case '20000':
                                        $twenty = $card['NUM'];
                                        break;
                                    case '30000':
                                        $thirty = $card['NUM'];
                                        break;

                                    case '50000':
                                        $fifty = $card['NUM'];
                                        break;
                                    case '100000':
                                        $hundred = $card['NUM'];
                                        break;
                                    case '200000':
                                        $twohun = $card['NUM'];
                                        break;
                                    case '500000':
                                        $fivehun = $card['NUM'];
                                        break;
                                    default:
                                        break;
                                }
                            }

                            ?>
                            <tr class="grade odd<?php echo $class; ?>">
                                <td><?php echo $ten;?></td>
                                <td><?php echo $twenty;?></td>
                                <td><?php echo $thirty;?></td>
                                <td><?php echo $fifty;?></td>
                                <td><?php echo $hundred;?></td>
                                <td><?php echo $twohun;?></td>
                                <td><?php echo $fivehun;?></td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </form>
    </div>
    <?php endif; ?>
</div>