<?php

/**
 * list.phtml
 *
 * list view file
 *
 * @project mvc
 * @author duong bien
 * @email bien.duongvan@yahoo.com
 * @date 16/7/2015
 * @time 11:41
 * @copyright 2015 Copyright duong bien
 * @license duong bien
 * @version 1.0.0
 */

?>
<div class="row">
    <div class="col-lg-12">
        <ul class="breadcrumb">
            <li><a href="<?php echo BASE_URL . 'admin' ?>">Quản trị</a></li>
            <li class="active"><?php echo $title;?></li>
        </ul>
    </div>
</div>

<div class="row">

    <div class="col-lg-12">

        <form action="" name="filterForm" method="post" id="filterForm">
            <div class="col-lg-12">
                <div class="row">
                    <div class="panel panel-default">
                        <div class="panel-heading"><i class="fa fa-search"></i> Lọc dữ liệu
                            <div class="btn-group pull-right" id="dropdown-toggle">
                                <button class="btn btn-default btn-xs" type="button">
                                    <i class="fa fa-chevron-down"></i>
                                </button>
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <?php
                                $currentMonth = date("m");
                                $currentYear = date("Y");
                                $months = array('01','02','03','04','05','06','07','08','09','10','11','12');
                                $years = array($currentYear,$currentYear-1,$currentYear-2,$currentYear-3);
                                ?>
                                <div class="col-sm-3">
                                    <div class="form-group small">
                                        <select class="" name="months" id="months">
                                            <option value="0">Chọn tháng</option>
                                            <?php foreach($months as $month):?>
                                                <option <?php if($data['months'] == $month) echo "selected";?> value="<?php echo $month;?>">Tháng <?php echo $month?></option>
                                            <?php endforeach;?>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-sm-3">
                                    <div class="form-group small">
                                        <select class="" name="years" id="years">
                                            <option value="0">Chọn năm</option>
                                            <?php foreach($years as $year):?>
                                                <option <?php if($data['years'] == $year) echo "selected";?> value="<?php echo $year;?>"><?php echo $year?></option>
                                            <?php endforeach;?>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-sm-2">
                                    <div class="form-group small">
                                        <input type="hidden" name="task" value="filter"/>
                                        <input class="btn btn-primary btn-sm" type="submit" value="Xem thống kê"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>

        <?php if (count($data['collection']) < 1): ?>
            <p class="no-data empty-data"><?php echo NODATA; ?></p>
            <?php if (!empty($data['description'])): ?>
                <p class="error-mess"><?php
                    $mbftext->__($data['description']); ?></p>
            <?php endif; ?>
        <?php else: ?>

        <form action="" name="" method="post" id="MyForm">
            <p style="text-align:center;font-size: 18px;font-weight: bold;color: red;margin-bottom: 15px;">Nợ xấu theo MỆNH GIÁ THẺ tính tới ngày <?php if (isset($data['t_date'])) : ?><?php echo $data['t_date']; ?><?php endif; ?></p><table id="dataTables-example" class="table table-striped table-bordered table-hover dataTable">
            <p class="error-mess"></p>
            <div class="col-sm-12">
                <div class="row">
                    <table id="dataTables-example" class="table table-striped table-bordered table-hover dataTable">
                        <thead>
                        <tr>

                            <th>Mệnh giá</th>
                            <th>Nợ xấu</th>
                            <th style = "display:none;">Tiền phí </th>
                            <th style = "display:none;">Gốc + phí</th>
                            <th>Số lượng thuê bao</th>
                            <th>Tỷ lệ % Nợ xấu (*)</th>
                            <th>Tỷ lệ % lượng thuê bao Nợ xấu (**)</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php $line = 0; ?>
                        <?php

                        ?>
                        <?php
                        /**
                         * array (size=8)
                        'CREATE_DATE' => string '29-12-2017 02:10:51' (length=19)
                        'CARD_AMOUNT' => string '10000' (length=5)
                        'ORG_DEBT' => string '10000' (length=5)
                        'FEE_DEBT' => string '2000' (length=4)
                        'TOTAL_DEBT' => string '12000' (length=5)
                        'TOTAL_SUBS' => string '1' (length=1)
                        'TOTAL_PERCENT' => int 100
                        'SUBS_PERCENT' => int 100
                         */

                        ?>
                        <?php foreach ($data['collection'] as $entry): ?>
                            <?php
                            $class = "";
                            if (($line % 2) == 0) $class .= " even-line";
                            else $class .= " odd-line";
                            if ($line == 0) $class .= " first";
                            $line++;
                            ?>
                            <tr class="grade odd<?php echo $class; ?>">
                                <td><?php echo number_format($entry['CARD_AMOUNT'])?><sub class="vnd">đ</sub></td>
								<td><?php echo number_format($entry['ORG_DEBT']); ?><sub class="vnd">đ</sub></td>
								<td style = "display:none;"><?php echo number_format($entry['FEE_DEBT']); ?><sub class="vnd">đ</sub></td>
								<td style = "display:none;"><?php echo number_format($entry['TOTAL_DEBT']); ?><sub class="vnd">đ</sub></td>
								<td><?php echo ($entry['TOTAL_SUBS']); ?></td>
								<td><?php echo number_format($entry['TOTAL_PERCENT'])?>%</td>
								<td><?php echo number_format($entry['SUBS_PERCENT'])?>%</td>
                            </tr>
                        <?php endforeach; ?>
                        <?php
                            $sum = $data['sum'];
                        ?>
							<tr style="font-weight:bold;">
								<td>Tổng toàn hệ thống: </td>
								<td><?php echo number_format($sum['no_xau']) ?><sub class="vnd">đ</sub></td>
								<td style = "display:none;"><?php echo number_format($sum['phi']) ?><sub class="vnd">đ</sub></td>
								<td style = "display:none;"><?php echo number_format($sum['tong']) ?><sub class="vnd">đ</sub></td>
								<td><?php echo ($sum['subs']) ?></td>
								<td><?php echo ($sum['tt_percent']) ?>%</td>
								<td><?php echo ($sum['subs_percent']) ?>%</td>
							</tr>
                        </tbody>
                    </table>

                </div>
            </div>
        </form>
    </div>
    <?php endif; ?>
    <br>
    <p class = "comment-field"> (*) Nợ xấu tháng T là những giao dịch vẫn chưa hoàn ứng trước 24:00:00 của "ngày cuối cùng" trong tháng T+1.</p>
    <p class = "comment-field"> (**) Tỷ lệ % Nợ xấu = Tổng tiền nợ xấu / Tổng tiền gốc đã ứng của hệ thống trong tháng</p>
    <p class = "comment-field"> (***) Tỷ lệ % lượng thuê bao Nợ xấu = số lượng thuê bao nợ xấu / tổng số thuê bao của hệ thống trong tháng</p>

</div>