<?php

/**
 * list.phtml
 *
 * list view file
 *
 * @project mvc
 * @author duong bien
 * @email bien.duongvan@yahoo.com
 * @date 16/7/2015
 * @time 11:41
 * @copyright 2015 Copyright duong bien
 * @license duong bien
 * @version 1.0.0
 */

?>
<div class="row">
    <div class="col-lg-12">
        <ul class="breadcrumb">
            <li><a href="<?php echo BASE_URL . 'admin' ?>">Quản trị</a></li>
            <li class="active">Báo cáo tổng quan</li>
        </ul>
    </div>
</div>

<div class="row">

    <div class="col-lg-12">

        <form action="" name="filterForm" method="post" id="filterForm">
            <div class="col-lg-12">
                <div class="row">
                    <div class="panel panel-default">
                        <div class="panel-heading"><i class="fa fa-search"></i> Lọc dữ liệu
                            <div class="btn-group pull-right" id="dropdown-toggle">
                                <button class="btn btn-default btn-xs" type="button">
                                    <i class="fa fa-chevron-down"></i>
                                </button>
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="row">

                                <div class="col-sm-3">
                                    <div class="form-group small">
                                        <label>Từ ngày</label>
                                        <input class="form-control small" name="f_date" id="f_date"
                                               placeholder="01/02/2017" onfocus="this.placeholder = ''
                                               onblur="this.placeholder = '01/02/2017'"
                                        value="<?php if (isset($data['f_date'])) : ?><?php echo $data['f_date']; ?><?php endif; ?>"/>
                                    </div>
                                </div>
                                <div class="col-sm-3">
                                    <div class="form-group small">
                                        <label>Đến ngày</label>
                                        <input class="form-control small" name="t_date" id="t_date"
                                               placeholder="01/02/2017" onfocus="this.placeholder = ''"
                                               onblur="this.placeholder = '01/02/2017'"
                                               value="<?php if (isset($data['t_date'])) : ?><?php echo $data['t_date']; ?><?php endif; ?>"/>
                                    </div>
                                </div>
                                <div class="col-sm-2">
                                    <div class="form-group small" style="margin-top: 20px;">
                                        <input type="hidden" name="task" value="filter"/>
                                        <input class="btn btn-primary btn-sm" type="submit" value="Xem Thống Kê"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>

        <?php if (count($data['collection']) < 1): ?>
            <p class="no-data empty-data"><?php echo NODATA; ?></p>
            <?php if (0): ?>
                <p class="error-mess"><?php echo "Mã kết quả trả về: " . $data['return_value']; ?></p>
                <p class="error-mess"><?php echo "Thông tin lỗi : ";
                    $mbftext->__($data['description']); ?></p>
            <?php endif; ?>
        <?php else: ?>

        <form action="" name="" method="post" id="MyForm">
            <div class="message-action">
            </div>
            <div class="col-sm-12">
                <div class="row">
                    <table id="dataTables-example" class="table table-striped table-bordered table-hover dataTable">
                        <thead>
                        <tr>
                            <th class="report-header" colspan="14">Thống kê từ ngày <?php if (isset($data['f_date'])) : ?><?php echo $data['f_date']; ?><?php endif; ?> đến ngày <?php if (isset($data['t_date'])) : ?><?php echo $data['t_date']; ?><?php endif; ?>
                            </th>

                        </tr>
                        <tr>
                            <th class="gdu" colspan="2">Thống kê giao dịch ứng</th>
                            <th class="gdhu" colspan="3">Thống kê giao dịch hoàn ứng</th>
                            <th class = '' colspan="2">Thống kê nợ </th>
                        </tr>
                        <tr>
                            <th class="gdu"><?php $mbftext->__('Số lượng ứng'); ?></th>
                            <th class="gdu"><?php $mbftext->__('Số tiền đã ứng'); ?></th>
                            <th class="gdhu"><?php $mbftext->__('Tiền hoàn ứng gốc'); ?></th>
                            <th class="gdhu"><?php $mbftext->__('Phí thu được'); ?></th>
                            <th class="gdhu"><?php $mbftext->__('Tổng tiền hoàn ứng(gốc+phí)'); ?></th>
                            <th class = ''><?php $mbftext->__('Nợ trong kỳ hạn'); ?></th>
                            <th class = ''><?php $mbftext->__('Nợ xấu'); ?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php $line = 0;?>
                        <?php foreach ($data['collection'] as $entry): ?>
                            <?php
                            $class = "";
                            if (($line % 2) == 0) $class .= " even-line";
                            else $class .= " odd-line";
                            if ($line == 0) $class .= " first";
                            $line++;
                            ?>
                            <tr class="grade odd<?php echo $class; ?> data-bold">
                                <td><?php echo $entry['sl_ung'];?></td>
                                <td><?php echo number_format($entry['tien_ung']) ?><sub class="vnd">đ</sub></td>
                                <td><?php echo number_format($entry['tien_hoan_ung_goc']) ?><sub class="vnd">đ</sub></td>
                                <td><?php echo number_format($entry['tien_hoan_ung_phi']) ?><sub class="vnd">đ</sub></td>
                                <td><?php echo number_format($entry['hoan_ung_tong']) ?><sub class="vnd">đ</sub></td>
                                <td><?php echo number_format($entry['no_bt']) ?><sub class="vnd">đ</sub></td>
                                <td><?php echo number_format($entry['no_xau']) ?><sub class="vnd">đ</sub></td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
                <br>
                <br>
                <div class="row">
                    <table id="dataTables-example" class="table table-striped table-bordered table-hover dataTable">
                        <thead>
                        <tr>
                            <th class = "khothe" colspan="7">Thống kê số lượng kho thẻ hiện tại</th>
                        </tr>
                        <tr>
                            <th class = "khothe">10k</th>
                            <th class = "khothe">20k</th>
                            <th class = "khothe">30k</th>
                            <th class = "khothe">50k</th>
                            <th class = "khothe">100k</th>
                            <th class = "khothe">200k</th>
                            <th class = "khothe">500k</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php $line = 0;?>
                        <?php foreach ($data['collection'] as $entry): ?>
                            <?php
                            $class = "";
                            if (($line % 2) == 0) $class .= " even-line";
                            else $class .= " odd-line";
                            if ($line == 0) $class .= " first";
                            $line++;
                            $cards = $entry['kho_the'];

                            $ten = 0;
                            $twenty = 0;
                            $thirty = 0;
                            $fifty = 0;
                            $hundred = 0;
                            $twohun = 0;
                            $fivehun = 0;
                            foreach ($cards as $card){
                                $amount = $card['AMOUNT'];
                                switch ($amount) {
                                    case '10000':
                                        $ten = $card['NUM']*$amount;
                                        break;
                                    case '20000':
                                        $twenty = $card['NUM']*$amount;
                                        break;

                                    case '30000':
                                        $thirty = $card['NUM']*$amount;
                                        break;
                                    case '50000':
                                        $fifty = $card['NUM']*$amount;
                                        break;
                                    case '100000':
                                        $hundred = $card['NUM']*$amount;
                                        break;
                                    case '200000':
                                        $twohun = $card['NUM']*$amount;
                                        break;
                                    case '500000':
                                        $fivehun = $card['NUM']*$amount;
                                        break;
                                    default:
                                        break;
                                }
                            }

                            ?>
                            <tr class="grade odd<?php echo $class; ?> data-bold">
                                <td><?php echo number_format($ten) ?><sub class="vnd">đ</sub></td>
                                <td><?php echo number_format($twenty) ?><sub class="vnd">đ</sub></td>
                                <td><?php echo number_format($thirty) ?><sub class="vnd">đ</sub></td>
                                <td><?php echo number_format($fifty) ?><sub class="vnd">đ</sub></td>
                                <td><?php echo number_format($hundred) ?><sub class="vnd">đ</sub></td>
                                <td><?php echo number_format($twohun) ?><sub class="vnd">đ</sub></td>
                                <td><?php echo number_format($fivehun) ?><sub class="vnd">đ</sub></td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </form>
    </div>
    <?php endif; ?>
</div>