<div class="row">
    <div class="col-lg-12">
        <div class="row">
            <ul class="breadcrumb">
                <li><a href="<?php echo BASE_URL.'admin'?>">Quản trị</a></li>
                <li class="active">index</li>
            </ul>
        </div>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
    <h3>QUẢN TRỊ DỊCH VỤ - <?php echo Core_Config::getConfig("web","service_name")?></h3>
</div>