<?php

/**
* list.phtml
* 
* list view file
* 
* @project mvc 
* @author duong bien
* @email bien.duongvan@yahoo.com 
* @date 16/7/2015
* @time 11:41
* @copyright 2015 Copyright duong bien
* @license duong bien
* @version 1.0.0
*/

?>
<div class="row">
    <div class="col-lg-12">
        <ul class="breadcrumb">
            <li><a href="<?php echo BASE_URL.'admin'?>">Quản trị</a></li>
            <li class="active">Danh sách logs tác động hệ thống</li>
        </ul>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
		<form action="" name="filterForm" method="post" id="filterForm">
            <div class="col-lg-12">
                <div class="row">
                    <div class="panel panel-default">
                        <div class="panel-heading"><i class="fa fa-search"></i> Lọc dữ liệu
                            <div class="btn-group pull-right" id="dropdown-toggle">
                                <button class="btn btn-default btn-xs" type="button">
                                    <i class="fa fa-chevron-down"></i>
                                </button>
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-sm-3">
                                    <div class="form-group small">
                                        <label>Nhập username</label>
                                        <input class="form-control small" name="username" id="username" value="<?php if (isset($exp['username'])) : ?><?php echo $exp['username']; ?><?php endif; ?>" />
										<input type="hidden" name="user_id" id="user_id" value="<?php if (isset($exp['user_id'])) : ?><?php echo $exp['user_id']; ?><?php endif; ?>" />
									</div>
                                </div>
								<div class="col-sm-3">
                                    <div class="form-group small">
                                        <label>Từ ngày</label>
                                        <input class="form-control small" name="f_date" id="f_date"
                                               value="<?php if (isset($data['f_date'])) : ?><?php echo date("d-m-Y", strtotime($data['f_date'])); ?><?php endif; ?>"/>
                                    </div>
                                </div>
                                <div class="col-sm-3">
                                    <div class="form-group small">
                                        <label>Đến ngày</label>
                                        <input class="form-control small" name="t_date" id="t_date"
                                               value="<?php if (isset($data['t_date'])) : ?><?php echo date("d-m-Y", strtotime($data['t_date'])); ?><?php endif; ?>"/>
                                    </div>
                                </div>
                                <div class="col-sm-2">
                                    <div class="form-group small" style="margin-top: 20px;">
                                        <input type="hidden" name="task" value="filter" />
										<input class="btn btn-primary btn-sm" type="submit" value="Xem" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
		
        <?php if(count($impactlogs) == 0):?>
            <p class="no-data"><?php echo NODATA;?></p>
        <?php else:?>

        <form action="" name="" method="post" id="MyForm">
            <div class="col-sm-12">
                <div class="row">
                    <table id="dataTables-example" class="table table-striped table-bordered table-hover dataTable">
                        <thead>
                            <tr>
								<th>ID</th>
                                <th>USER ID</th>
								<th>USER NAME</th>
								<th>LOCATION</th>
								<th>DATE TIME</th>
								<th>DESCRIPTION</th>
								<th>IP</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php foreach($impactlogs as $row):?>
                            <tr class="grade odd">
								<td><?php echo $row['LOG_ID'];?></td>
								<td><?php echo $row['USER_ID'];?></td>
								<td><?php echo $row['USERNAME'];?></td>
                                <td><?php echo $row['LOCATION'];?></td>
								<td><?php echo date('d-m-Y H:i:s', strtotime($row['CREATE_DATE']))?></td>
								<td><?php echo $row['DESCRIPTIONS'];?></td>
                                <td><?php echo $row['IP'];?></td>
                            </tr>
                            
                        <?php endforeach;?>
                        </tbody>
                    </table>
                </div>
            </div>
        </form>
    </div>
    <?php endif;?>

</div>

<script type="text/javascript">

$(document).ready(function() {
    $('#filterForm').validate({
		rules: {
			username: {
				//required: true
			}
	    },
	    messages: {
	    	// Enter custom error text here.
		}
	});
	
	$("#f_date").datepicker({
		dateFormat: 'dd-mm-yy',
		showAnim: 'slideDown',
		onSelect: function (selected) {
			$("#t_date").datepicker("option", "minDate", selected)
		}
	});

	$("#t_date").datepicker({
		dateFormat: 'dd-mm-yy',
		showAnim: 'slideDown',
		onSelect: function (selected) {
			$("#f_date").datepicker("option", "maxDate", selected)
		}
	});
	
	$("#username").autocomplete({
        source: "<?php echo BASE_URL."user/suggest"; ?>",
        minLength: 1,
        autoFocus: true,
        select: function( event, ui ) {
            //alert(ui.item.id);
            $(this).val(ui.item.value);
            $("#user_id").val(ui.item.id);
            return false;
        },
    });  
    
});

</script>