<?php

/**
* list.phtml
* 
* list view file
* 
* @project mvc 
* @author duong bien
* @email bien.duongvan@yahoo.com 
* @date 16/7/2015
* @time 11:41
* @copyright 2015 Copyright duong bien
* @license duong bien
* @version 1.0.0
*/

?>
<div class="row">
    <div class="col-lg-12">
        <ul class="breadcrumb">
            <li><a href="<?php echo BASE_URL.'admin'?>">Quản trị</a></li>
            <li class="active">Lịch chạy process</li>
        </ul>
    </div>
</div>

<div class="row">

    <div class="col-lg-12">
		
		<form action="" name="filterForm" method="post" id="filterForm">
            <div class="col-lg-12">
                <div class="row">
                    <div class="panel panel-default">
                        <div class="panel-heading"><i class="fa fa-search"></i> Lọc dữ liệu
                            <div class="btn-group pull-right" id="dropdown-toggle">
                                <button class="btn btn-default btn-xs" type="button">
                                    <i class="fa fa-chevron-down"></i>
                                </button>
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-sm-3">
                                    <div class="form-group small">
                                        <label>Nhập số điện thoại</label>
                                        <input placeholder="918014988" onfocus="this.placeholder = ''" onblur="this.placeholder = '918014988'" class="form-control small" name="msisdn" id="msisdn" value="<?php if (isset($data['msisdn'])) : ?><?php echo $data['msisdn']; ?><?php endif; ?>" />
                                    </div>
                                </div>
								<div class="col-sm-3">
                                    <div class="form-group small">
                                        <label>Từ ngày</label>
                                        <input class="form-control small" name="f_date" id="f_date"
                                               value="<?php if (isset($data['f_date'])) : ?><?php echo date("d-m-Y", strtotime($data['f_date'])); ?><?php endif; ?>"/>
                                    </div>
                                </div>
                                <div class="col-sm-3">
                                    <div class="form-group small">
                                        <label>Đến ngày</label>
                                        <input class="form-control small" name="t_date" id="t_date"
                                               value="<?php if (isset($data['t_date'])) : ?><?php echo date("d-m-Y", strtotime($data['t_date'])); ?><?php endif; ?>"/>
                                    </div>
                                </div>
                                <div class="col-sm-2">
                                    <div class="form-group small" style="margin-top: 20px;">
                                        <input type="hidden" name="task" value="filter" />
										<input class="btn btn-primary btn-sm" type="submit" value="Tra cứu" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
		
        <?php if($data['curs'] == null):?>
            <p class="no-data"><?php echo NODATA;?></p>
        <?php else:?>

		<?php //print_r($data['curs']);?>
        <form action="" name="" method="post" id="MyForm">
            <div class="col-sm-12">
                <div class="row">
                    <table id="dataTables-example" class="table table-striped table-bordered table-hover dataTable">
                        <thead>
                            <tr>
                                <th class="text-center">Mã giao dịch hoàn ứng</th>
								<th class="text-center">Mã giao dịch ứng</th>
								<th class="text-center">Mã nợ</th>
								<th class="text-center">Mã thuê bao</th>
								<th class="text-center">Số thuê bao</th>
								<th class="text-center">Số tiền nạp</th>
								<th class="text-center">Số tiền đã hoàn ứng</th>
								<th class="text-center">SMS gửi KH</th>
								<th class="text-center">Hạn hoàn ứng</th>
								<th class="text-center">Nợ xấu</th>
                            </tr>
                        </thead>
                        <tbody>
                        <tr class="grade odd">
							<?php $row = $data['curs'];?>
							<td class="text-center"><?php echo $row->PAYMENT_TRANS_ID?></td>
							<td class="text-center"><?php echo $row->CREDIT_TRANS_ID?></td>
							<td class="text-center"><?php echo $row->SUBS_DEBT_ID?></td>
							<td class="text-center"><?php echo $row->SUB_ID?></td>
							<td class="text-center"><?php echo $row->MSISDN?></td>
							<td class="text-center"><?php echo number_format($row->RECHARGE_CARD_AMOUNT)?>đ</td>
							<td class="text-center"><?php echo number_format($row->PAYMENT_CARD_AMOUNT + $row->PAYMENT_FEE_AMOUNT)?>đ</td>
							<td class="text-center"><textarea class="form-control"><?php echo $row->SMS?></textarea></td>
							<td class="text-center"><?php echo date('d/m/Y H:i:s', strtotime($row->PAYMENT_DATE))?></td>
							<td class="text-center"><?php echo ($row->BAD_DEBT == 0) ? 'Nợ trong kỳ đối soát' : 'Nợ xấu không đối soát';?></td>
						</tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </form>
    </div>
    <?php endif;?>

</div>

<script type="text/javascript">

$(document).ready(function() {
    $('#filterForm').validate({
		rules: {
			msisdn: {
				required: true
			}
	    },
	    messages: {
	    	// Enter custom error text here.
		}
	});
	
	$("#f_date").datepicker({
		dateFormat: 'dd-mm-yy',
		showAnim: 'slideDown',
		onSelect: function (selected) {
			$("#t_date").datepicker("option", "minDate", selected)
		}
	});

	$("#t_date").datepicker({
		dateFormat: 'dd-mm-yy',
		showAnim: 'slideDown',
		onSelect: function (selected) {
			$("#f_date").datepicker("option", "maxDate", selected)
		}
	});
    
});

</script>