<?php

/**
* list.phtml
* 
* list view file
* 
* @project mvc 
* @author duong bien
* @email bien.duongvan@yahoo.com 
* @date 16/7/2015
* @time 11:41
* @copyright 2015 Copyright duong bien
* @license duong bien
* @version 1.0.0
*/

?>
<div class="row">
    <div class="col-lg-12">
        <ul class="breadcrumb">
            <li><a href="<?php echo BASE_URL.'admin'?>">Quản trị</a></li>
            <li class="active">Tra cứu process excution</li>
        </ul>
    </div>
</div>

<div class="row">

    <div class="col-lg-12">
		
		<form action="" name="filterForm" method="post" id="filterForm">
            <div class="col-lg-12">
                <div class="row">
                    <div class="panel panel-default">
                        <div class="panel-heading"><i class="fa fa-search"></i> Lọc dữ liệu
                            <div class="btn-group pull-right" id="dropdown-toggle">
                                <button class="btn btn-default btn-xs" type="button">
                                    <i class="fa fa-chevron-down"></i>
                                </button>
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-sm-3">
                                    <div class="form-group small">
                                        <label>Chọn tháng</label>
                                        <select id = "proccess_months" name="proccess_months">
                                            <option value="">---Chọn tháng---</option>
                                            <?php for($i = 1;$i < 13;$i++){ ?>
                                                <option <?php if((int) $data['month'] == $i) echo "selected"; ?> value="<?php if($i < 10) echo "0".$i; else echo $i; ?>">Tháng <?php echo $i;?></option>
                                           <?php }; ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-sm-3">
                                    <div class="form-group small">
                                        <label>Chọn năm</label>
                                        <select id = "proccess_years" name="proccess_years">
                                            <?php
                                                $currentYear = date("Y");
                                            ?>
                                            <option value="">---Chọn năm---</option>
                                            <?php for($i = $currentYear-2;$i < $currentYear+3;$i++){ ?>
                                                <option <?php if((int) $data['year'] == $i) echo "selected"; ?> value="<?php echo $i; ?>">Năm <?php echo $i;?></option>
                                            <?php }; ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-sm-2">
                                    <div class="form-group small" style="margin-top: 20px;">
                                        <input type="hidden" name="task" value="filter" />
										<input class="btn btn-primary btn-sm" type="submit" value="Tra cứu" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>

        <?php if (count($data['collection']) < 1): ?>
            <p class="no-data empty-data"><?php echo NODATA; ?></p>
            <?php if ((int)$data['return_value'] != 1 && !empty($data['msisdn'])): ?>
                <p class="error-mess"><?php echo "Mã kết quả trả về: " . $data['return_value']; ?></p>
                <p class="error-mess"><?php echo "Thông tin lỗi : ";
                    $mbftext->__($data['description']); ?></p>
            <?php endif; ?>
        <?php else: ?>

        <form action="" name="" method="post" id="MyForm">
            <p class="success-mess">Tổng số <?php echo count($data['collection']); ?> bản ghi được tìm thấy.</p>
            <p class="error-mess"></p>
            <div class="col-sm-12">
                <div class="row">
                    <table id="dataTables-example" class="table table-striped table-bordered table-hover dataTable">
                        <thead>
                        <tr>
                            <th>TÊN PROCESS</th>
                            <th>PROCESS ID</th>
                            <th>KHỞI CHẠY</th>
                            <th>KẾT THÚC</th>
                            <th>EXEC SCHEDULE TIME</th>
                            <th>TRẠNG THÁI</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php $line = 0; ?>
                        <?php
                        /**
                         * 'PROCESS_NAME' => string 'Import du lieu tieu dung thang T-1' (length=34)
                        'PROCESS_ID' => string '1' (length=1)
                        'STARTED_TIME' => string '07-01-2018 17:17:29' (length=19)
                        'COMPLETED_TIME' => string '07-01-2018 17:19:18' (length=19)
                        'EXEC_SCHEDULE_TIME' => string '01-01-2018 00:00:00' (length=19)
                        'STATUS' => string 'Completed Success' (length=17)
                         */
                        ?>
                        <?php foreach ($data['collection'] as $entry): ?>
                            <?php
                            $class = "";
                            if (($line % 2) == 0) $class .= " even-line";
                            else $class .= " odd-line";
                            if ($line == 0) $class .= " first";
                            $line++;
                            ?>
                            <tr class="grade odd<?php echo $class; ?>">
                                <td><?php echo $entry['PROCESS_NAME'] ?></td>
                                <td><?php echo $entry['PROCESS_ID'] ?></td>
                                <td><?php echo date("d/m/Y", strtotime($entry['STARTED_TIME'])) ?></td>
                                <td><?php echo date("d/m/Y", strtotime($entry['COMPLETED_TIME'])) ?></td>
                                <td><?php echo date("d/m/Y", strtotime($entry['EXEC_SCHEDULE_TIME'])) ?></td>
                                <td><?php echo $entry['STATUS'] ?></td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </form>
    </div>
    <?php endif;?>

</div>

<script type="text/javascript">

$(document).ready(function() {
    $('#filterForm').validate({
		rules: {
			msisdn: {
				required: true
			}
	    },
	    messages: {
	    	// Enter custom error text here.
		}
	});
	
	$("#f_date").datepicker({
		dateFormat: 'dd-mm-yy',
		showAnim: 'slideDown',
		onSelect: function (selected) {
			$("#t_date").datepicker("option", "minDate", selected)
		}
	});

	$("#t_date").datepicker({
		dateFormat: 'dd-mm-yy',
		showAnim: 'slideDown',
		onSelect: function (selected) {
			$("#f_date").datepicker("option", "maxDate", selected)
		}
	});
    
});

</script>