<?php

/**
* edit.phtml
* 
* edit view file
* 
* @project mvc 
* @author duong bien
* @email bien.duongvan@yahoo.com 
* @date 16/7/2015
* @time 11:39
* @copyright 2015 Copyright duong bien
* @license duong bien
* @version 1.0.0
*/
?>
<div class="row">
    <div class="col-lg-12">
        <div class="row">
        <ul class="breadcrumb">
            <li><a href="<?php echo BASE_URL.'admin'?>">Quản trị</a></li>
            <li><a href="<?php echo BASE_URL.'defineagelevel/list'?>">Danh sách định nghĩa mức tuổi thọ</a></li>
            <li class="active">Sửa định nghĩa mức tuổi thọ</li>
        </ul>
     </div>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
    <div class="panel panel-default">
        <div class="panel-heading">
            <i class="fa fa-edit fa-fw"></i> 
            Nhập các thông tin về định nghĩa mức tuổi thọ vào form dưới đây:
        </div>
        <div class="panel-body">
            <form action="" id="editForm" method="post" enctype="multipart/form-data">
                <div class="col-lg-12">
                    <div class="row">
                        <div class="col-lg-8">
                            <input type="hidden" name="task" value="edit" />
                            
                            <div class="form-group">
                                <label>MIN EQUAL DAYS</label>
                                <input class="form-control" type="text" name="min_equal_days" id="min_equal_days" value="<?php echo $data->MIN_EQUAL_DAYS;?>" />
                            </div>
							<div class="form-group">
                                <label>MAX LESS DAYS</label>
                                <input class="form-control" type="text" name="max_less_days" id="max_less_days" value="<?php echo $data->MAX_LESS_DAYS;?>" />
                            </div>
							<div class="form-group">
                                <label>CARD AMOUNT</label>
                                <input class="form-control" type="text" name="card_amount" id="card_amount" value="<?php echo $data->CARD_AMOUNT;?>" />
                            </div>
							<div class="form-group">
                                <label>BIT POS</label>
                                <input class="form-control" type="text" name="bit_pos" id="bit_pos" value="<?php echo $data->BIT_POS;?>" />
                            </div>
							<div class="form-group">
                                <label>DESCRIPTION</label>
                                <textarea class="form-control" name="des" id="des"><?php echo $data->DES;?></textarea>
                            </div>
                            <div class="form-group">
                                <input class="btn btn-primary btn-sm" type="submit" value="Lưu" />
                            </div>
                            
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script type="text/javascript">

$(document).ready(function() {
    $('#editForm').validate({
		rules: {
			min_equal_days: {
				required: true,
			},
			max_less_days: {
				required: true
			},
			card_amount: {
				required: true,
			},
			bit_pos: {
				required: true
			},
			des: {
				required: true
			}
	    },
	    messages: {
	    	// Enter custom error text here.
		}
	});
});

</script>