
<?php

/**
 * add.phtml
 *
 * add view file
 *
 * @project mvc
 * @author duong bien
 * @email bien.duongvan@yahoo.com
 * @date 16/7/2015
 * @time 11:38
 * @copyright 2015 Copyright duong bien
 * @license duong bien
 * @version 1.0.0
 */

?>
<div class="row">
    <div class="col-lg-12">
        <div class="row">
            <ul class="breadcrumb">
                <li><a href="<?php echo BASE_URL.'admin'?>">Quản trị</a></li>
                <li><a href="<?php echo BASE_URL.'system/config'?>">Hệ thống</a></li>
            </ul>
        </div>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
    <div class="panel panel-default">
        <div class="panel-heading">
            <i class="fa fa-edit fa-fw"></i>
            Cập nhật thông tin hệ thống:
        </div>
        <div class="panel-body">
            <form action="" id="configForm" method="post" enctype="multipart/form-data">
                <div class="col-lg-12">
                    <div class="row">
                        <div class="col-lg-8">
                            <div class="form-group">
                                <label>Tên công ty</label>
                                <input class="form-control" type="text" name="site_name" id="site_name" value="<?php echo $site_name;?>" />
                            </div>
                            <div class="form-group">
                                <label>Url Logo</label>
                                <input class="form-control" type="text" name="logo" id="logo" value="<?php echo $logo;?>" />
                            </div>
                            <div class="form-group">
                                <label>Tên dịch vụ</label>
                                <input class="form-control" type="text" name="service_name" id="service_name" value="<?php echo $service_name;?>" />
                            </div>
                            <div class="form-group">
                                <label>Tiêu đề mặc định</label>
                                <input class="form-control" type="text" name="default_title" id="default_title" value="<?php echo $default_title;?>" />
                            </div>
                            <div class="form-group">
                                <label>Bản quyền</label>
                                <input class="form-control" type="text" name="copyright" id="copyright" value="<?php echo $copyright;?>" />
                            </div>
                            <div class="form-group">
                                <label>Địa chỉ</label>
                                <input class="form-control" type="text" name="address" id="address" value="<?php echo $address;?>" />
                            </div>
                            <div class="form-group">
                                <label>Hotline</label>
                                <input class="form-control" type="text" name="hotline" id="hotline" value="<?php echo $hotline;?>" />
                            </div>
                            <div class="form-group">
                                <label>Email</label>
                                <input class="form-control" type="email" name="email" id="email" value="<?php echo $email;?>" />
                            </div>

                            <div class="form-group">
                                <input type="hidden" name="task" value="edit">
                                <input class="btn btn-primary btn-sm" type="submit" value="Lưu cấu hình" />
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>