<?php

/**
* list.phtml
* 
* list view file
* 
* @project mvc 
* @author duong bien
* @email bien.duongvan@yahoo.com 
* @date 16/7/2015
* @time 11:41
* @copyright 2015 Copyright duong bien
* @license duong bien
* @version 1.0.0
*/

?>
<div class="row">
    <div class="col-lg-12">
        <ul class="breadcrumb">
            <li><a href="<?php echo BASE_URL.'admin'?>">Quản trị</a></li>
            <li class="active">Bù thẻ mới do khiếu nại</li>
        </ul>
    </div>
</div>
Viết Fuction call
<div class="row hidden">
<?php if(count($ErrorCode) == 0):?>
<div class="col-sm-12 bottom-10">
	<div class="">
		<?php if($acl->allow("complain","add")):?>
		<a href="<?php echo BASE_URL.'complain/add'?>" class="btn btn-primary btn-sm pull-right">Thêm ErrorCode mới</a>
		<?php endif;?>
	</div>
</div>
<p class="no-data"><?php echo NODATA;?></p>
<?php else:?>
    <div class="col-lg-12">  
        <form action="" name="" method="post" id="MyForm">
			<div class="col-sm-12 bottom-10">
				<div class="row">
					<?php if($acl->allow("errorcode","add")):?>
					<a href="<?php echo BASE_URL.'errorcode/add'?>" class="btn btn-primary btn-sm pull-right">Thêm ErrorCode mới</a>
					<?php endif;?>
					<?php if($acl->allow("errorcode","delete")):?>
					<input onclick="gotoAction('delete','errorcode');" type="submit" disabled="" id="delete" class="btn-action btn btn-danger btn-sm pull-right right-10" value="Xóa" />
                    <?php endif;?>
					<?php if($acl->allow("errorcode","edit")):?>
					<input onclick="gotoAction('edit','errorcode');" type="submit" disabled="" id="edit" class="btn-action btn btn-success btn-sm pull-right right-10"  value="Sửa" />
					<?php endif;?>
					<input type="hidden" name="task-list" value="submit" />
				</div>
			</div>
            <div class="col-sm-12">
                <div class="row">
                    <table id="dataTables-example" class="table table-striped table-bordered table-hover dataTable">
                        <thead>
                            <tr>
								<th class="text-center" style="width:15px;"><input id="checkall" class="ids" onclick="checkAll('ids[]',this);" type="checkbox" /></th>
                                <th style="width: 200px;">ERROR CODE</th>
                                <th>ERROR DES</th>
								<th>MESSAGE</th>
								<th>SYSTEM</th>
								<th>FUNCTION</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php foreach($ErrorCode as $row):?>
                            <tr class="grade odd">
								<td class="text-center"><input type="checkbox" id="ids" class="ids" value="<?php echo $row['ERROR_CODE'];?>" name="ids[]" /></td>
                                <td><?php echo $row['ERROR_CODE'];?></td>
								<td><?php echo $row['ERROR_DES'];?></td>
                                <td><?php echo $row['MESSAGE'];?></td>
								<td><?php echo $row['SYSTEM'];?></td>
                                <td><?php echo $row['FUNCTION'];?></td>
                            </tr>
                            
                        <?php endforeach;?>
                        </tbody>
                    </table>
                </div>
            </div>
        </form>
    </div>
<?php endif;?>
</div>
