<?php

/**
* add.phtml
* 
* add view file
* 
* @project mvc 
* @author duong bien
* @email bien.duongvan@yahoo.com 
* @date 16/7/2015
* @time 11:38
* @copyright 2015 Copyright duong bien
* @license duong bien
* @version 1.0.0
*/

?>
<div class="row">
    <div class="col-lg-12">
        <div class="row">
            <ul class="breadcrumb">
                <li><a href="<?php echo BASE_URL.'admin'?>">Quản trị</a></li>
                <li><a href="javascript">Đưa thuê bao vào black list</a></li>
            </ul>
            <?php if(isset($message) && ($message != null)):?>
            <div class="alert alert-success alert-dismissable">
                <button aria-hidden="true" data-dismiss="alert" class="close" type="button">x</button>
                <?php echo $message;?>
            </div>
            <?php endif;?>
        </div>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
    <div class="panel panel-default">
        <div class="panel-heading">
            <i class="fa fa-edit fa-fw"></i> 
            Nhập số thuê bao vào form dưới đây:
        </div>
        <div class="panel-body">
            <form action="" id="addForm" method="post" enctype="multipart/form-data">
                <div class="col-lg-12">
                    <div class="row">
                        <div class="col-lg-8">
                            <div class="form-group">
                                <label>Nhập số thuê bao</label>
                                <input class="form-control" placeholder="918014988" onfocus="this.placeholder = ''" onblur="this.placeholder = '918014988'" class="form-control small" name="msisdn" id="msisdn" type="text" />
                            </div>
							<?php if(count($black_list_reason)>0):?>
                            <div class="form-group">
                                <label>Chọn lý do black list</label>
                                <select class="form-control" name="reason_code" id="reason_code">
                                    <option value="">----</option>
                                    <?php foreach($black_list_reason as $row):?>
                                    <option value="<?php echo $row['REASON_CODE'];?>"><?php echo $row['REASON_NAME'];?></option>
                                    <?php endforeach;?>
                                </select>
                            </div> 
                            <?php endif;?>
							<div class="form-group">
                                <label>Mô tả</label>
                                <textarea class="form-control" name="des" id="des"></textarea>
                            </div>
                            <div class="form-group">
                                <input class="btn btn-primary btn-sm" type="submit" value="Thêm" />
                            </div>                   
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script type="text/javascript">

$(document).ready(function() {
    $('#addForm').validate({
		ignore: ':not(select:hidden, input:visible, textarea:visible)',
		rules: {
			msisdn: {
				required: true,
				remote: '<?php echo BASE_URL.'complain/check?check_type=msisdn';?>'
			},
			des: {
				required: true,
			},
			reason_code: {
				required: true,
			},
	    },
	    messages: {
	    	// Enter custom error text here.
		}
	});
});

</script>