<?php

/**
* add.phtml
* 
* add view file
* 
* @project mvc 
* @author duong bien
* @email bien.duongvan@yahoo.com 
* @date 16/7/2015
* @time 11:38
* @copyright 2015 Copyright duong bien
* @license duong bien
* @version 1.0.0
*/

?>
<div class="row">
    <div class="col-lg-12">
        <div class="row">
            <ul class="breadcrumb">
                <li><a href="<?php echo BASE_URL.'admin'?>">Quản trị</a></li>
                <li><a href="<?php echo BASE_URL.'controlsystem/list'?>">Tra cứu event log</a></li>
                <li class="active">Tạo trigger</li>
            </ul>
        </div>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
<?php if(count($collection) == 0):?>
<p class="no-data"><?php echo NODATA;?></p>
<?php else:?>
    <div class="col-lg-12">  
        <form action="" name="" method="post" id="MyForm">
            <div class="col-sm-12">
                <div class="row">
                    <table id="dataTables-example" class="table table-striped table-bordered table-hover dataTable">
                        <thead>
                            <tr>
								<th style="width:300px;">EVENT CODE</th>
                                <th>EVENT NAME</th>
								<th>PROCESS CLASS</th>
								<th>OPTIONS</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php foreach($collection as $row):?>
                            <tr class="grade odd">
								<td><?php echo $row['EVENT_CODE'];?></td>
                                <td><?php echo $row['EVENT_NAME'];?></td>
								<td><?php echo $row['PROCESS_CLASS'];?></td>
								<td><input onclick="AddEvent('<?php echo $row['EVENT_CODE'];?>'); return;" class="btn btn-primary btn-sm" type="button" value="Tạo Event"/></td>
                            </tr>
                        <?php endforeach;?>
                        </tbody>
                    </table>
                </div>
            </div>
        </form>
    </div>
<?php endif;?>
</div>

<script type="text/javascript">

function AddEvent(event_code){

   //alert(event_code);return;
   $.ajax({
		url: '<?php echo BASE_URL.'controlsystem/insert'?>',
		type: 'POST',
		data: {
			EVENT_CODE: event_code
		},
		success: function(data){
			//alert(data);
			if(data == 1){
				alert('Tạo Event thành công.');
			}else{
				alert('Tạo Event thất bại.');
			}
		}
   });
}

</script>