<?php

/**
* list.phtml
* 
* list view file
* 
* @project mvc 
* @author duong bien
* @email bien.duongvan@yahoo.com 
* @date 16/7/2015
* @time 11:41
* @copyright 2015 Copyright duong bien
* @license duong bien
* @version 1.0.0
*/

?>
<div class="row">
    <div class="col-lg-12">
        <ul class="breadcrumb">
            <li><a href="<?php echo BASE_URL.'admin'?>">Quản trị</a></li>
            <li class="active">Lịch sử gửi SMS mã thẻ</li>
        </ul>
    </div>
</div>

<div class="row">
<?php if(count($Creditsent) == 0):?>
<div class="col-sm-12 bottom-10">
	<div class="">

	</div>
</div>
<p class="no-data"><?php echo NODATA;?></p>
<?php else:?>
    <div class="col-lg-12">  
        <form action="" name="" method="post" id="MyForm">

            <div class="col-sm-12">
                <div class="row">
                    <table id="dataTables-example" class="table table-striped table-bordered table-hover dataTable">
                        <thead>
                            <tr>
								<th class="text-center" style="width:15px;"><input id="checkall" class="ids" onclick="checkAll('ids[]',this);" type="checkbox" /></th>
                                <th>REASON CODE</th>
                                <th>REASON NAME</th>
								<th>CREATE DATE</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php foreach($BlacklistReason as $row):?>
                            <tr class="grade odd">
								<td class="text-center"><input type="checkbox" id="ids" class="ids" value="<?php echo $row['REASON_CODE'];?>" name="ids[]" /></td>
                                <td><?php echo $row['REASON_CODE'];?></td>
								<td><?php echo $row['REASON_NAME'];?></td>
                                <td><?php echo date('d-m-Y H:i:s', strtotime($row['CREATE_DATE'])) ?></td>
                            </tr>
                            
                        <?php endforeach;?>
                        </tbody>
                    </table>
                </div>
            </div>
        </form>
    </div>
<?php endif;?>
</div>
