<?php

/**
* list.phtml
* 
* list view file
* 
* @project mvc 
* @author duong bien
* @email bien.duongvan@yahoo.com 
* @date 16/7/2015
* @time 11:41
* @copyright 2015 Copyright duong bien
* @license duong bien
* @version 1.0.0
*/

?>
<div class="row">
    <div class="col-lg-12">
        <ul class="breadcrumb">
            <li><a href="<?php echo BASE_URL.'admin'?>">Quản trị</a></li>
            <li class="active">Cấu hình quy tắc ứng thẻ</li>
        </ul>
    </div>
</div>

<div class="row">
<?php if(count($definerules) == 0):?>
<p class="no-data"><?php echo NODATA;?></p>
<?php else:?>
    <div class="col-lg-12">  
        <form action="" name="" method="post" id="MyForm">
			<div class="col-sm-12 bottom-10">
				<div class="row">
					<?php if($acl->allow("definerules","edit")):?>
					<input onclick="gotoAction('edit','definerules');" type="submit" disabled="" id="edit" class="btn-action btn btn-success btn-sm pull-right right-10"  value="Sửa" />
					<?php endif;?>
					<input type="hidden" name="task-list" value="submit" />
				</div>
			</div>
            <div class="col-sm-12">
                <div class="row">
                    <table id="dataTables-example" class="table table-striped table-bordered table-hover dataTable">
                        <thead>
                            <tr>
								<th class="text-center" style="width:15px;"><input id="checkall" class="ids" onclick="checkAll('ids[]',this);" type="checkbox" /></th>
                                <th>RULE ID</th>
                                <th>RULE NAME</th>
								<th>BLOCK POS</th>
								<th>BREAK LEVEL TABLE</th>
                                <th>SUBS BIT POS TABLE</th>
								<th>STATUS</th>
								<th>PARTITON TIME TYPE</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php foreach($definerules as $row):?>
                            <tr class="grade odd">
								<td class="text-center"><input type="checkbox" id="ids" class="ids" value="<?php echo $row['RULE_ID'];?>" name="ids[]" /></td>
                                <td><?php echo $row['RULE_ID'];?></td>
								<td><?php echo $row['RULE_NAME'];?></td>
                                <td><?php echo $row['BLOCK_POS'];?></td>
								<td><?php echo $row['BREAK_LEVEL_TABLE'];?></td>
								<td><?php echo $row['SUBS_BIT_POS_TABLE'];?></td>
                                <td><?php echo $row['STATUS'];?></td>
								<td><?php echo $row['PARTITON_TIME_TYPE'];?></td>
                            </tr>
                            
                        <?php endforeach;?>
                        </tbody>
                    </table>
                </div>
            </div>
        </form>
    </div>
<?php endif;?>
</div>
