<?php

/**
 * list.phtml
 *
 * list view file
 *
 * @project mvc
 * @author duong bien
 * @email bien.duongvan@yahoo.com
 * @date 16/7/2015
 * @time 11:41
 * @copyright 2015 Copyright duong bien
 * @license duong bien
 * @version 1.0.0
 */

?>
<div class="row">
    <div class="col-lg-12">
        <ul class="breadcrumb">
            <li><a href="<?php echo BASE_URL . 'admin' ?>">Quản trị</a></li>
            <li class="active"><?php echo $title; ?></li>
        </ul>
    </div>
</div>

<div class="row">

    <div class="col-lg-12">

        <form action="" name="filterForm" method="post" id="filterForm">
            <div class="col-lg-12">
                <div class="row">
                    <div class="panel panel-default">
                        <div class="panel-heading"><i class="fa fa-search"></i> Lọc dữ liệu
                            <div class="btn-group pull-right" id="dropdown-toggle">
                                <button class="btn btn-default btn-xs" type="button">
                                    <i class="fa fa-chevron-down"></i>
                                </button>
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-sm-3">
                                    <div class="form-group small">
                                        <label>Từ ngày</label>
                                        <input class="form-control small" name="f_date" id="f_date"
                                               placeholder="01/02/2017" onfocus="this.placeholder = ''
                                               onblur=" this.placeholder='01/02/2017'"
                                        value="<?php if (isset($data['f_date'])) : ?><?php echo $data['f_date']; ?><?php endif; ?>
                                        "/>
                                    </div>
                                </div>
                                <div class="col-sm-3">
                                    <div class="form-group small">
                                        <label>Đến ngày</label>
                                        <input class="form-control small" name="t_date" id="t_date"
                                               placeholder="01/02/2017" onfocus="this.placeholder = ''"
                                               onblur="this.placeholder = '01/02/2017'"
                                               value="<?php if (isset($data['t_date'])) : ?><?php echo $data['t_date']; ?><?php endif; ?>"/>
                                    </div>
                                </div>
                                <div class="col-sm-2">
                                    <div class="form-group small" style="margin-top: 20px;">
                                        <input type="hidden" name="task" value="filter"/>
                                        <input class="btn btn-primary btn-sm" type="submit" value="Xem thống kê"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>

        <?php if (empty($data['chartdata'])): ?>
            <p class="no-data empty-data"><?php echo NODATA; ?></p>
            <?php if (!empty($data['description'])): ?>
            <p class="error-mess"><?php echo "Thông tin lỗi : ";
                $mbftext->__($data['description']); ?></p>
        <?php endif; ?>
        <?php else: ?>
            <p style="text-align:center;font-size: 18px;font-weight: bold;color: red;margin-bottom: 15px;">Thống kê số lượng giao dịch nợ xấu từng ngày từ ngày <?php if (isset($data['f_date'])) : ?><?php echo $data['f_date']; ?><?php endif; ?>
                đến ngày <?php if (isset($data['t_date'])) : ?><?php echo $data['t_date']; ?><?php endif; ?>
            </p>
            <script type="text/javascript" src="<?php echo SKIN_URL; ?>/admin/dist/js/google-chart.js"></script>
            <div id="columnchart_material_noxau" class="report-chart bad-debt debt body-chart"
                 style="width: 800px; height: 600px;"></div>
            <script type="text/javascript">
                google.charts.load('current', {'packages': ['bar']});
                google.charts.setOnLoadCallback(drawChart);

                function drawChart() {
                    var data = google.visualization.arrayToDataTable([
                        ['Ngày', 'Tất cả', '10K', '20K', '30K', '50K', '100K', '200K', '500K'],
                        <?php echo $data['chartdata'];?>
                    ]);
                    var formatNumer = new google.visualization.NumberFormat({pattern: 'decimal'});
                    formatNumer.format(data, 0);
                    formatNumer.format(data, 1);
                    formatNumer.format(data, 2);
                    formatNumer.format(data, 3);
                    formatNumer.format(data, 4);
                    formatNumer.format(data, 5);
                    formatNumer.format(data, 6);
                    formatNumer.format(data, 7);
                    formatNumer.format(data, 8);
                    var options = {
                        chart: {
                            title: 'Đối chiếu số lượng giao dịch nợ xấu',
                            subtitle: 'Đối chiếu số lượng giao dịch nợ xấu',
                        },
                        vAxis: {title: 'Số lượng giao dịch'}

                    };

                    var chart = new google.charts.Bar(document.getElementById('columnchart_material_noxau'));

                    chart.draw(data, google.charts.Bar.convertOptions(options));
                }
            </script>
        <?php endif; ?>
    </div>

</div>