<?php

/**
 * list.phtml
 *
 * list view file
 *
 * @project mvc
 * @author duong bien
 * @email bien.duongvan@yahoo.com
 * @date 16/7/2015
 * @time 11:41
 * @copyright 2015 Copyright duong bien
 * @license duong bien
 * @version 1.0.0
 */

?>
<div class="row">
    <div class="col-lg-12">
        <ul class="breadcrumb">
            <li><a href="<?php echo BASE_URL . 'admin' ?>">Quản trị</a></li>
            <li class="active"><?php echo $title; ?></li>
        </ul>
    </div>
</div>

<div class="row">

    <div class="col-lg-12">

        <form action="" name="filterForm" method="post" id="filterForm">
            <div class="col-lg-12">
                <div class="row">
                    <div class="panel panel-default">
                        <div class="panel-heading"><i class="fa fa-search"></i> Lọc dữ liệu
                            <div class="btn-group pull-right" id="dropdown-toggle">
                                <button class="btn btn-default btn-xs" type="button">
                                    <i class="fa fa-chevron-down"></i>
                                </button>
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-sm-3">
                                    <div class="form-group small">
                                        <label>Từ ngày</label>
                                        <input class="form-control small" name="f_date" id="f_date"
                                               placeholder="01/02/2017" onfocus="this.placeholder = ''
                                               onblur="this.placeholder = '01/02/2017'"
                                        value="<?php if (isset($data['f_date'])) : ?><?php echo $data['f_date']; ?><?php endif; ?>"/>
                                    </div>
                                </div>
                                <div class="col-sm-3">
                                    <div class="form-group small">
                                        <label>Đến ngày</label>
                                        <input class="form-control small" name="t_date" id="t_date"
                                               placeholder="01/02/2017" onfocus="this.placeholder = ''"
                                               onblur="this.placeholder = '01/02/2017'"
                                               value="<?php if (isset($data['t_date'])) : ?><?php echo $data['t_date']; ?><?php endif; ?>"/>
                                    </div>
                                </div>
                                <div class="col-sm-2">
                                    <div class="form-group small" style="margin-top: 20px;">
                                        <input type="hidden" name="task" value="filter"/>
                                        <input class="btn btn-primary btn-sm" type="submit" value="Xem thống kê"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>

        <?php if (count($data['chartdata']) < 1): ?>
            <p class="no-data empty-data"><?php echo NODATA; ?></p>
            <?php if (!empty($data['description'])): ?>
                <p class="error-mess"><?php
                    $mbftext->__($data['description']); ?></p>
            <?php endif; ?>
        <?php else: ?>
            <p style="text-align:center;font-size: 18px;font-weight: bold;color: green;margin-bottom: 15px;">Số lượng giao dịch nợ xấu theo từng mệnh giá thẻ từ ngày <?php if (isset($data['f_date'])) : ?><?php echo $data['f_date']; ?><?php endif; ?>
                 đến ngày <?php if (isset($data['t_date'])) : ?><?php echo $data['t_date']; ?><?php endif; ?>
            </p>
        <script type="text/javascript" src="<?php echo SKIN_URL; ?>/admin/dist/js/google-chart.js"></script>
        <div id="columnchart_month_noxau" class="report-chart bad-debt debt body-chart"
             style="width: 800px; height: 600px;"></div>
        <script type="text/javascript">
            google.charts.load('current', {'packages': ['bar']});
            google.charts.setOnLoadCallback(drawChart);

            function drawChart() {
                var data = google.visualization.arrayToDataTable([
                    ['Ngày', 'Tất cả', '10K', '20K', '30K', '50K', '100K', '200K', '500K'],
                    <?php echo $data['chartdata'];?>
                ]);
                var formatNumer = new google.visualization.NumberFormat({pattern: 'decimal'});
                formatNumer.format(data, 0);
                formatNumer.format(data, 1);
                formatNumer.format(data, 2);
                formatNumer.format(data, 3);
                formatNumer.format(data, 4);
                formatNumer.format(data, 5);
                formatNumer.format(data, 6);
                formatNumer.format(data, 7);
                formatNumer.format(data, 8);
                var options = {
                    chart: {
                        title: 'Tiền nợ xấu theo từng mệnh giá thẻ',
                        subtitle: 'Tiền nợ xấu theo từng mệnh giá thẻ',
                    },
                    vAxis: {title: 'Số tiền'}
                };

                var chart = new google.charts.Bar(document.getElementById('columnchart_month_noxau'));

                chart.draw(data, google.charts.Bar.convertOptions(options));
            }
        </script>
        <br>
        <?php $total = $data['total'][0];?>
        <?php if(!empty($total)): ?>
            <div class = "pecent-talbe">
                <p class="success-mess align-center">Đối chiếu số lượng giao dịch và tỷ lệ % nợ xấu của từng mệnh giá thẻ / Tổng nợ xấu</p>
                <div class="col-sm-12">
                    <div class="row">
                        <table id="pecent-talbe" class="table table-striped table-bordered table-hover dataTable">
                            <thead>
                            <tr>
                                <th>Đối chiếu</th>
                                <th>Tất cả mệnh giá</th>
                                <th>10K</th>
                                <th>20K</th>
                                <th>30K</th>
                                <th>50K</th>
                                <th>100K</th>
                                <th>200K</th>
                                <th>500K</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr style="font-weight:bold;">
                                <td>Số lượng giao dịch</td>
                                <td><?php echo number_format($total['all']) ?></td>
                                <td><?php echo number_format($total['10k']) ?></td>
                                <td><?php echo number_format($total['20k']) ?></td>
                                <td><?php echo number_format($total['30k']) ?></td>
                                <td><?php echo number_format($total['50k']) ?></td>
                                <td><?php echo number_format($total['100k']) ?></td>
                                <td><?php echo number_format($total['200k']) ?></td>
                                <td><?php echo number_format($total['500k']) ?></td>
                            </tr>
                            <tr style="font-weight:bold;">
                                <td>Tỷ lệ %</td>
                                <td></td>
                                <td><?php echo number_format(($total['10k']*100)/$total['all'],3) ?>%</td>
                                <td><?php echo number_format(($total['20k']*100)/$total['all'],3) ?>%</td>
                                <td><?php echo number_format(($total['30k']*100)/$total['all'],3) ?>%</td>
                                <td><?php echo number_format(($total['50k']*100)/$total['all'],3) ?>%</td>
                                <td><?php echo number_format(($total['100k']*100)/$total['all'],3) ?>%</td>
                                <td><?php echo number_format(($total['200k']*100)/$total['all'],3) ?>%</td>
                                <td><?php echo number_format(($total['500k']*100)/$total['all'],3) ?>%</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <br>
        <?php endif;?>

        <br>
        <p class="comment-field"> (*) Nợ xấu đối soát mỗi tháng một lần, nợ xấu tháng T là những giao dịch vẫn chưa hoàn ứng trước 24:00:00 của "ngày cuối
            cùng" trong tháng T+1.</p>
            <!--<p class="comment-field"> (**) Tỷ lệ % Nợ xấu = Tổng tiền nợ xấu / Tổng tiền gốc đã ứng của hệ thống trong
                tháng</p>
            <p class="comment-field"> (***) Tỷ lệ % lượng thuê bao Nợ xấu = số lượng thuê bao nợ xấu / tổng số thuê bao của
                hệ thống trong tháng</p>-->

    </div>
    <?php endif; ?>

</div>