<?php

/**
 * list.phtml
 *
 * list view file
 *
 * @project mvc
 * @author duong bien
 * @email bien.duongvan@yahoo.com
 * @date 16/7/2015
 * @time 11:41
 * @copyright 2015 Copyright duong bien
 * @license duong bien
 * @version 1.0.0
 */

?>
<div class="row">
    <div class="col-lg-12">
        <ul class="breadcrumb">
            <li><a href="<?php echo BASE_URL . 'admin' ?>">Quản trị</a></li>
            <li class="active"><?php echo $mbftext->__('Tra cứu lịch sử chạy tổng hợp báo cáo'); ?></li>
        </ul>
    </div>
</div>

<div class="row">

    <div class="col-lg-12">

        <form action="" name="filterForm" method="post" id="filterForm">
            <div class="col-lg-12">
                <div class="row">
                    <div class="panel panel-default">
                        <div class="panel-heading"><i class="fa fa-search"></i> Lọc dữ liệu
                            <div class="btn-group pull-right" id="dropdown-toggle">
                                <button class="btn btn-default btn-xs" type="button">
                                    <i class="fa fa-chevron-down"></i>
                                </button>
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="row">
								 <div class="col-sm-3">
									<?php if(count($report_type)>0):?>
									<div class="form-group">
										<label>Loại báo cáo</label>
										<select class="form-control" name="p_reportID" id="p_reportID">
											<option value="">----</option>
											<?php foreach($report_type as $row):?>
											<option <?php if($p_reportID == $row['REPORT_ID']):?> selected="" <?php endif;?> value="<?php echo $row['REPORT_ID'];?>"><?php echo $row['REPORT_NAME'];?> - (Report ID: <?php echo $row['REPORT_ID'];?> - Loại báo cáo: <?php echo ($row['REPORT_DATE_TYPE'] == 'D') ? 'Ngày' : 'Tháng';?>)</option>
											<?php endforeach;?>
										</select>
									</div> 
									<?php endif;?>
								</div>
                                <div class="col-sm-3">
                                    <div class="form-group small">
                                        <label>Dữ liệu từ ngày</label>
                                        <input class="form-control small" name="f_date" id="f_date"
                                               placeholder="01/02/2017" onfocus="this.placeholder = ''"
                                               onblur="this.placeholder = '01/02/2017'"
                                               value="<?php if (isset($data['f_date'])) : ?><?php echo $data['f_date']; ?><?php endif; ?>"/>
                                    </div>
                                </div>
                                <div class="col-sm-3">
                                    <div class="form-group small">
                                        <label>Dữ liệu đến ngày</label>
                                        <input class="form-control small" name="t_date" id="t_date"
                                               placeholder="01/02/2017" onfocus="this.placeholder = ''"
                                               onblur="this.placeholder = '01/02/2017'"
                                               value="<?php if (isset($data['t_date'])) : ?><?php echo $data['t_date']; ?><?php endif; ?>"/>
                                    </div>
                                </div>
                                <div class="col-sm-2">
                                    <div class="form-group small" style="margin-top: 20px;">
                                        <input type="hidden" name="task" value="filter"/>
                                        <input class="btn btn-primary btn-sm" type="submit" value="Tra cứu"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>

        <?php if (count($data['collection']) < 1): ?>
            <p class="no-data empty-data"><?php echo NODATA; ?></p>
            <?php if ((int)$data['return_value'] != 1 && !empty($data['msisdn'])): ?>
                <p class="error-mess"><?php echo "Mã kết quả trả về: " . $data['return_value']; ?></p>
                <p class="error-mess"><?php echo "Thông tin lỗi : ";
                    $mbftext->__($data['description']); ?></p>
            <?php endif; ?>
        <?php else: ?>

        <?php //print_r($data['curs']);?>
        <form action="" name="" method="post" id="MyForm">
            <p class="success-mess">Tổng số <?php echo count($data['collection']); ?> bản ghi được tìm thấy.</p>
            <div class="col-sm-12">
                <div class="row">
                    <table id="dataTables-example" class="table table-striped table-bordered table-hover dataTable">
                        <thead>
                        <tr>
                            <th><?php $mbftext->__("FROM_DATA_DATE"); ?></th>
                            <th><?php $mbftext->__("TO_DATA_DATE"); ?></th>
                            <th><?php $mbftext->__("RUN_DATE"); ?></th>
                            <th><?php $mbftext->__("RESULT_RECORDS"); ?></th>
                            <th style="min-width:60px;"><?php $mbftext->__("STATUS"); ?></th>
							<th><?php $mbftext->__("DES"); ?></th>
                            <th><?php $mbftext->__("SQL_TEXT"); ?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr class="grade odd">

                        </tr>
                        </tbody>
                        <tbody>
                        <?php $line = 0; ?>
                        <?php foreach ($data['collection'] as $entry): ?>
                            <?php
                            $class = "";
                            if (($line % 2) == 0) $class .= " even-line";
                            else $class .= " odd-line";
                            if ($line == 0) $class .= " first";
                            $line++;
                            ?>
                            <tr class="grade odd<?php echo $class; ?>">
                                <td><?php echo date("d-m-Y", strtotime($entry['FROM_DATA_DATE']) ); ?></td>
								<td><?php echo date("d-m-Y", strtotime($entry['TO_DATA_DATE']) ); ?></td>
                                <td><?php echo $entry['RUN_DATE'] ?></td>
                                <td><?php echo $entry['REPORT_RESULT_RECORDS'] ?></td>
                                <td><?php echo ($entry['STATUS'] == 1) ? 'OK' : 'NOT OK'; ?></td>
                                <td><?php echo $entry['DES'] ?></td>
                                <td><?php echo $entry['SQL_TEXT'] ?></td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </form>
    </div>
    <?php endif; ?>

</div>
