<?php

/**
* add.phtml
* 
* add view file
* 
* @project mvc 
* @author duong bien
* @email bien.duongvan@yahoo.com 
* @date 16/7/2015
* @time 11:38
* @copyright 2015 Copyright duong bien
* @license duong bien
* @version 1.0.0
*/

?>
<div class="row">
    <div class="col-lg-12">
        <div class="row">
            <ul class="breadcrumb">
                <li><a href="<?php echo BASE_URL.'admin'?>">Quản trị</a></li>
                <li><a href="<?php echo BASE_URL.'errorcode/list'?>">Danh sách ErrorCode</a></li>
                <li class="active">Thêm ErrorCode mới</li>
            </ul>
            <?php if(isset($message) && ($message != null)):?>
            <div class="alert alert-success alert-dismissable">
                <button aria-hidden="true" data-dismiss="alert" class="close" type="button">x</button>
                <?php echo $message;?>
            </div>
            <?php endif;?>
        </div>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
    <div class="panel panel-default">
        <div class="panel-heading">
            <i class="fa fa-edit fa-fw"></i> 
            Nhập các thông tin về ErrorCode vào form dưới đây:
        </div>
        <div class="panel-body">
            <form action="" id="addErrorCodeForm" method="post" enctype="multipart/form-data">
                <div class="col-lg-12">
                    <div class="row">
                        <div class="col-lg-8">
                            <div class="form-group">
                                <label>ERROR CODE</label>
                                <input class="form-control" type="text" name="error_code" id="error_code" />
                            </div>
							<div class="form-group">
                                <label>ERROR DES</label>
                                <textarea class="form-control" name="error_des" id="error_des"></textarea>
                            </div>
							<div class="form-group">
                                <label>MESSAGE</label>
                                <textarea rows="15" class="form-control" name="message" id="message"></textarea>
                            </div>
							<div class="form-group">
                                <label>SYSTEM</label>
                                <input class="form-control" type="text" name="system" id="system" />
                            </div>
							<div class="form-group">
                                <label>FUNCTION</label>
                                <input class="form-control" type="text" name="_function" id="_function" />
                            </div>
                            <div class="form-group">
                                <input class="btn btn-primary btn-sm" type="submit" value="Lưu" />
                            </div>                   
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script type="text/javascript">

$(document).ready(function() {
    $('#addErrorCodeForm').validate({
		rules: {
			error_code: {
				required: true,
				remote: '<?php echo BASE_URL.'errorcode/check?check_type=error_code';?>'
			},
			error_des: {
				required: true
			},
			message: {
				required: true
			},
			system: {
				required: true
			},
			_function: {
				required: true
			}
	    },
	    messages: {
	    	// Enter custom error text here.
		}
	});
});

</script>